### ISSUE TITLE
PlanModifiers called after Validators

### ISSUE THREAD

**Issue by appilon** [hashicorp/terraform-plugin-framework#125]
### Module version

```
github.com/hashicorp/terraform-plugin-framework v0.2.1-0.20210901173855-1778b4037415

(HEAD of main as of writing)
```

### Relevant provider source code

```go
...
"email_encoding_key": {
	Type:     types.StringType,
	Optional: true,
	Computed: true,
	Validators: []tfsdk.AttributeValidator{
		stringInSlice{slice: picklists.EmailEncodingKeys},
	},
	PlanModifiers: tfsdk.AttributePlanModifiers{
		defaultEmailEncodingKey{},
	},
},
...
func (defaultEmailEncodingKey) Modify(_ context.Context, req tfsdk.ModifyAttributePlanRequest, resp *tfsdk.ModifyAttributePlanResponse) {
	if req.AttributePlan.(types.String).Null {
		resp.AttributePlan = types.String{
			Value: "UTF-8",
		}
	}
}
```

### Terraform Configuration Files

```hcl
resource "example_user" "example" {
 # omitting email_encoding_key
}
```

### Expected Behavior

Default value should be supplied to Terraform and Validation called afterward

### Actual Behavior

Validation is called before plan modification, thus tripping the validation failure
```
╷
│ Error: Invalid string
│
│   with example_user.example,
│   on main.tf line 5, in resource "example_user" "example":
│    5: resource "example_user" "example" {
│
│ String must be one of: [UTF-8, ISO-8859-1]
╵
```
☝️ Also because field is intentionally omitted, the error will not point to a specific attribute in source

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by kmoe** [comment]
This happens because we handle each RPC in the order Terraform Core sends them: first,  we receive `ValidateResourceTypeConfig` and run the attribute validators, then we receive `PlanResourceChange` and run the attribute plan modifiers.

![Terraform resource lifecycle flowchart](https://github.com/hashicorp/terraform/raw/3b6c1ef156387e6652ed8516bce2af2422b7fcf1/docs/images/resource-instance-change-lifecycle.png)

SDKv2 is also subject to these limitations, but it has first-class functionality for default values: the default value of an attribute is calculated every time the instance state is accessed (see [`ConfigFieldReader.readPrimitive()`](https://github.com/hashicorp/terraform-plugin-sdk/blob/b147a9f54fd47093899df31c9d5a29eeb4b10fbe/helper/schema/field_reader_config.go#L227), which is the value returned from [`ResourceData.State()`](https://github.com/hashicorp/terraform-plugin-sdk/blob/b147a9f54fd47093899df31c9d5a29eeb4b10fbe/helper/schema/resource_data.go#L314)). In SDKv2, therefore, validation and plan customisations are always performed on top of the default values.

I think this issue is really about proper support for default values. @appilon, can you think of any other reason for wanting to run `PlanModifiers` before `Validators`?

@paddycarver and @bflad, how do you feel about first-class default value support in the framework - which I suppose would be some sort of `Attribute.Defaulters` business if we want to follow the same interface pattern everywhere?

**Comment by appilon** [comment]
Thank you for such a detailed response @kmoe ! Yes first class default support is important IMO, If it could be extended to the provider block also that would be great (I know PlanModifiers is only for resources, not data-sources/provider blocks).

As for validating after modification in general, off the top of my head can't really think of anything specific, performing some kind of normalization of the config and then performing validation on it? I suppose if the old SDK was subject to the same limitations then I won't be able to think of something that worked in the old SDK that doesn't now (other than the defaults).

**Comment by paddycarver** [comment]
> how do you feel about first-class default value support in the framework - which I suppose would be some sort of `Attribute.Defaulters` business if we want to follow the same interface pattern everywhere?

I would be interested in understanding what it helps providers do that PlanModifiers can't do more flexibly already. 😄

**Comment by paddycarver** [comment]
> performing some kind of normalization of the config and then performing validation on it?

I think it's worth pointing out that validation is done against values from the configuration, and plan modification changes the values in the plan, so plan modification doesn't really allow for normalizing the config. Nothing does, as far as I can tell. Normalizing configuration values is, I believe, kind of the province of custom types.

**Comment by appilon** [comment]
@paddycarver For the first comment, as it stands you can't implement defaults at all in a provider as described in the ticket?

**Comment by appilon** [comment]
For the second comment, I see what you are saying, normalization could happen in the Create/Update functions, this would cause a mismatch between remote and local state though, how do we tell terraform that local state should be different without throwing an error? Would that happen in `PlanModifers` by performing "diff suppression?

**Comment by apparentlymart** [comment]
Thinking though the various different interacting rules for what `PlanResourceChange` is allowed to do, FWIW it does seem to me like this is _in effect_ limited to the situation of inserting default values, because:

* Only `Optional`+`Computed` attributes allow for the provider to replace a null value in the configuration with a non-null value in the plan.
* Even _if_ an attribute is `Optional`+`Computed`, the provider isn't allowed to select a different value than the input if the configuration has anything other than a null value for that attribute.

I think the subtlety here, which leads to the question of what is the best order to run these validations, is that from Terraform's perspective "default values" are just a special case of `Computed` where the provider happens to know the concrete value in the `PlanResourceChange` response, rather than in the `ApplyResourceChange` response. Therefore Terraform isn't really "thinking about" that possibility when it calls `ValidateResourceConfig`: that operation is specifically for deciding if the _configuration_ is valid, regardless of prior state and what the remote system might ultimately want to contribute to the result.

I'm not sure exactly what conclusion to draw from this, but based on this thought experiment my initial intuition is that validation for an optional attribute that happens to accept one of a fixed set of values should always consider null as a valid value because it's optional, regardless of what other validation rules might be present.

That makes me think about just treating null values for optional arguments as _always_ valid during `ValidateResourceConfig`, without calling into the attribute-specific validation function at all, because declaring something as optional means that we'll select a default value for it either during plan or during apply, _not_ that we'll select it during validation. (Note that Terraform only requires a set of diagnostics from `ValidateResourceConfig`, _not_ any sort of modified/derived value like `PlanResourceChange` must produce, so there's no protocol-imposed requirement to select a default value for an optional argument during the validate step.)

**Comment by paddycarver** [comment]
> @paddycarver For the first comment, as it stands you can't implement defaults at all in a provider as described in the issue? (if validation is also present, very common for ENUM like string fields where there's a default and the user can specify alternatives from a list of options)

But any defaults we implemented would be built on top of the existing functionality, and would inherit those constraints?

Also, if validation handles the null case, then I don't see why it couldn't implement both validation and plan customization?

> For the second comment, I see what you are saying, normalization could happen in the Create/Update functions, this would cause a mismatch between remote and local state though, how do we tell terraform that local state should be different without throwing an error? Would that happen in PlanModifers by performing diff suppression?

I'm saying you can't modify the config at all, it's a read-only value. For normalization, we'd need to dig into what you mean a bit more. Do you have an example we can talk about?

> That makes me think about just treating null values for optional arguments as always valid during ValidateResourceConfig

For clarification here, do you mean in Terraform core or in the framework? Regardless, I think that would be semi-limiting, as (for example) I could currently define a validation function that says an attribute is required iff another attribute is set. If `null` is always valid we lose that capability.

I'm suspicious that the answer to this is going to be a `Default`/`DefaultFunc` helper implementation of `AttributePlanModifier` that does this for provider developers, but I'd like to hear more about the problem we're discussing. I think there's some confusion because SDKv2-only concepts aren't mirrored exactly here, but I think we've built the foundation they require.

In my head, at least, the code reported with the issue looks like this:

```go
...
"email_encoding_key": {
	Type:     types.StringType,
	Optional: true,
	Computed: true,
	Validators: []tfsdk.AttributeValidator{
		stringInSlice{slice: picklists.EmailEncodingKeys},
	},
	PlanModifiers: tfsdk.AttributePlanModifiers{
		defaultEmailEncodingKey{},
	},
},
...
// stringInSlice wasn't provided, so I spiked something out here
type stringInSlice struct {
  slice []string
}

func (s stringInSlice) Description(_ context.Context) string {
  return "Only accepts the following values: "+strings.Join(s.slice, ",")
}

func (s stringInSlice) MarkdownDescription(ctx context.Context) string {
  return s.Description(ctx)
}

func (s stringInSlice) Validate(ctx context.Context, req tfsdk.ValidateAttributeRequest, resp *tfsdk.ValidateAttributeResp) {
  val, ok := req.AttributeConfig.(types.String)
  if !ok {
    resp.Diagnostics = append(resp.Diagnostics, &tfprotov6.Diagnostic{
      Severity: tfprotov6.DiagnosticSeverityError,
      Summary: "Invalid type",
      Detail: fmt.Sprintf("This is always a provider error. Please report it to the provider:\n\nExpected type %T, got %T", types.String{}, req.AttributeConfig),
      Attribute: req.AttributePath,
    })
    return
  }
  if val.Null {
    return
  }
  for _, candidate := range s.slice {
    if candidate == val.Value {
      return
    }
  }
  resp.Diagnostics = append(resp.Diagnostics, &tfprotov6.Diagnostic{
    Severity: tfprotov6.DiagnosticSeverityError,
    Summary: "Invalid value",
    Detail: "Only the following values are accepted: "+strings.Join(s.slice, ","),
    Attribute: req.AttributePath,
  })
}

func (defaultEmailEncodingKey) Modify(_ context.Context, req tfsdk.ModifyAttributePlanRequest, resp *tfsdk.ModifyAttributePlanResponse) {
	if req.AttributePlan.(types.String).Null {
		resp.AttributePlan = types.String{
			Value: "UTF-8",
		}
	}
}
```

I typed that out in the GitHub comment box, but that's what I would expect an implementation like this to look like? It is, indeed, verbose right now, but my hope is that the diagnostics work landing soon and building up a library of helpers will make it much more palatable in size. But I think verbose and not possible are two different problems.

**Comment by kmoe** [comment]
>> That makes me think about just treating null values for optional arguments as always valid during ValidateResourceConfig (@apparentlymart)

> For clarification here, do you mean in Terraform core or in the framework? Regardless, I think that would be semi-limiting, as (for example) I could currently define a validation function that says an attribute is required iff another attribute is set. If null is always valid we lose that capability. (@paddycarver)

Paddy's solution in which the null check happens in the `stringInSlice` validator looks like it should solve the problem described in the issue, and is in my opinion the correct place for null handling. I agree that always counting null as valid on `Optional`+`Computed` attributes, or not running the validators, would be unnecessarily limiting.

---

> Also because field is intentionally omitted, the error will not point to a specific attribute in source (from initial issue description by @appilon)

I think this is also solved in Paddy's code example by including `Path: req.AttributePath` in the diag returned by the validator.

---

Alex also mentions that it there is no way to use AttributePlanModifiers to set default values on data sources or providers, which is true. Validators are obviously not suitable either as they cannot modify values (as Martin notes). This is worth a separate issue so we can dig into the use case. @appilon, would you mind opening another issue for the case of default values on non-resources?

**Comment by appilon** [comment]
Thanks everyone I do agree with these conclusions, I'll open an issue regarding defaults for datasource/provider block!

**Comment by appilon** [comment]
After some extra thought, plantime defaults are a nice to have on provider/datasource blocks but not really urgent since there's no visual component to provider blocks (at plantime). Defaults are achievable in the `Read` and `Configure` functions for those types respectively. It would be a nice to have but not even worth opening an issue for at the moment
