### ISSUE TITLE
Add testing practices to the contributing guide

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-framework#135]
@bflad pointed out that we don't really write down anywhere our preferences around testing. We should, in the CONTRIBUTING.md guide, write down our practices of using table-driven tests and calling `t.Parallel` (or documenting why a test can't be run in parallel, when it absolutely can't be avoided).

**Comment by bflad** [comment]
I'm not sure about enforcing table-driven tests, but the [`paralleltest` linter](https://github.com/kunwardeep/paralleltest/) baked into golangci-lint is probably a good candidate for enforcing `t.Parallel()` usage and ensuring the variable rescoping occurs. See also: #96 

---

This isn't done today yet, but a good debugging strategy from @paddycarver in unit testing is considering the following for diagnostics output:

```go
if diff := cmp.Diff(got.Diagnostics, tc.expectedDiags); diff != "" {
	for _, d := range got.Diagnostics {
		t.Log(d.Detail)
	}
	t.Errorf("Unexpected diff in diagnostics (+wanted, -got): %s", diff)
}
```

This is because `go-cmp` compresses long strings automatically without an easy way to override the behavior beyond creating a custom formatter. Either which way (`t.Log()` or using custom formatter), we should document and try to enforce it.
