### ISSUE TITLE
Computed-Only Schema Returns Configuration Read Error During Validation

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-framework#157]
### Module version

```
v0.3.0
```

### Relevant provider source code

Discovered while poking at https://github.com/hashicorp/terraform-plugin-framework/issues/105. Defining `ConfigValidators` in this case is most likely a red herring, but it is how I came across the issue in case it matters.

Adding following test case in `TestServerValidateResourceConfig`:

```go
		"no_config": {
			config:       tftypes.NewValue(testServeResourceTypeNoConfigType, map[string]tftypes.Value{}),
			impl:         func(_ context.Context, req ValidateResourceConfigRequest, resp *ValidateResourceConfigResponse) {},
			resource:     "test_no_config",
			resourceType: testServeResourceTypeNoConfigType,
			//
			// The below is unexpected!
			//
			expectedDiags: []*tfprotov6.Diagnostic{
				{
					Summary:   "Configuration Read Error",
					Severity:  tfprotov6.DiagnosticSeverityError,
					Detail:    "An unexpected error was encountered trying to read an attribute from the configuration. This is always an error in the provider. Please report the following to the provider developer:\n\nAttributeName(\"id\") still remains in the path: step cannot be applied to this value",
					Attribute: tftypes.NewAttributePath().WithAttributeName("id"),
				},
			},
		},
```

And creating an associated resource with only a computed attribute:

```go
package tfsdk

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

type testServeResourceTypeNoConfig struct{}

func (t testServeResourceTypeNoConfig) GetSchema(_ context.Context) (Schema, diag.Diagnostics) {
	return Schema{
		Attributes: map[string]Attribute{
			"id": {
				Type:     types.StringType,
				Computed: true,
			},
		},
	}, nil
}

func (t testServeResourceTypeNoConfig) NewResource(_ context.Context, p Provider) (Resource, diag.Diagnostics) {
	provider, ok := p.(*testServeProvider)
	if !ok {
		prov, ok := p.(*testServeProviderWithMetaSchema)
		if !ok {
			panic(fmt.Sprintf("unexpected provider type %T", p))
		}
		provider = prov.testServeProvider
	}
	return testServeResourceNoConfig{
		provider: provider,
	}, nil
}

var testServeResourceTypeNoConfigSchema = &tfprotov6.Schema{
	Block: &tfprotov6.SchemaBlock{
		Attributes: []*tfprotov6.SchemaAttribute{
			{
				Name:     "id",
				Computed: true,
				Type:     tftypes.String,
			},
		},
	},
}

var testServeResourceTypeNoConfigType = tftypes.Object{AttributeTypes: map[string]tftypes.Type{}}

type testServeResourceNoConfig struct {
	provider *testServeProvider
}

func (r testServeResourceNoConfig) Create(ctx context.Context, req CreateResourceRequest, resp *CreateResourceResponse) {
}
func (r testServeResourceNoConfig) Read(ctx context.Context, req ReadResourceRequest, resp *ReadResourceResponse) {
}
func (r testServeResourceNoConfig) Update(ctx context.Context, req UpdateResourceRequest, resp *UpdateResourceResponse) {
}
func (r testServeResourceNoConfig) Delete(ctx context.Context, req DeleteResourceRequest, resp *DeleteResourceResponse) {
}

func (r testServeResourceNoConfig) ConfigValidators(ctx context.Context) []ResourceConfigValidator {
	r.provider.validateResourceConfigCalledResourceType = "test_no_config"

	return []ResourceConfigValidator{
		newTestResourceConfigValidator(r.provider.validateResourceConfigImpl),
		// Verify multiple validators
		newTestResourceConfigValidator(r.provider.validateResourceConfigImpl),
	}
}
```

### Terraform Configuration Files

In the given test case, it would be:

```hcl
resource "test_no_config" "example" {}
```

### Expected Behavior

No `id` attribute error. This attribute has a valid definition.

In terms of the entire resource definition, either no error (validation skips the `id` attribute in this case, so succeeds) or the framework potentially returns an error saying that `ConfigValidators` cannot be specified when no attributes are configurable (`Optional`/`Required`).

### Actual Behavior

Unexpected validation error with the `id` attribute, which is defined as `Computed` only in the schema. I'm guessing the same also applies for `Provider` (similar to what #105 describes) and `DataSource`, but I have not verified. I'm unsure if this is possible in practice since I'm not sure if the `Config` data might have a null value for the `Computed` only attribute (although that seems like it would be an odd implementation detail). 

### Additional Context

This issue is probably conflating separate, but related problems for consideration (if `Config` does not include `Computed` only attributes):

- What to do if resource/datasource/provider-level validation is declared on schemas with no possible configuration (all attributes are `Computed` only)
- What to do if attribute-level validation is declared on schemas with no possible configuration (attribute is `Computed` only)

I think we will need to decide what the correct behavior of the framework is:

1. Not change anything and return the existing attribute-level error (seems fairly unclear to both provider developers and practitioners, in my opinion)
2. Skip `Computed`-only attributes during validation, since validation is only configuration-based at the moment
3. Return a different error that captures the case of a schema that cannot have configuration but includes configuration validation (resource/datasource/provider `ConfigValidators`/`ValidateConfig` or attribute `Validators`)

### Steps to Reproduce

1. Add above Go code in `tfsdk/`
2. Run `go test -count=1 ./tfsdk`

### References

- Potentially similar in nature to #105
- Some potential fix implementation details may relate to #113

**Comment by bflad** [comment]
4. A potential variation of skipping Computed only attributes during validation may be to change the Configuration Read Error into a well-defined Diagnostic type and instead skipping validation when receiving that Diagnostic type.

**Comment by paddycarver** [comment]
> I'm unsure if this is possible in practice since I'm not sure if the Config data might have a null value for the Computed only attribute (although that seems like it would be an odd implementation detail).

My understanding is that config includes computed-only attributes and sets them as null at validate time, and the framework transforms them to be unknown automatically at plan time. I think this because config and state and plan are always supposed to conform to the schema, and omitting an attribute changes the type completely, so if computed-only attributes were omitted, we wouldn't be able to decode them using their schema types.

> What to do if resource/datasource/provider-level validation is declared on schemas with no possible configuration (all attributes are Computed only)

That feels like an error for something like #113 to handle and perhaps an eventual linter to catch.

> What to do if attribute-level validation is declared on schemas with no possible configuration (attribute is Computed only)

Same, feels like a #113 and/or linter thing to raise.

> I think we will need to decide what the correct behavior of the framework is:

I prefer a combination of 2 and 3. I think we skip computed-only attributes when running validation, and I think InternalValidate handles the edge case of "we skipped everything".

I think this test case is a wrong fixture. This line:

```go
			config:       tftypes.NewValue(testServeResourceTypeNoConfigType, map[string]tftypes.Value{}),
```

should be

```go
			config:       tftypes.NewValue(testServeResourceTypeNoConfigType, map[string]tftypes.Value{
				"id": tftypes.NewValue(tftypes.String, nil),
			}),
```

by my understanding. Practitioners should never actually see this error, as far as I can tell, because we should never have a null or empty config like this, unless the schema is empty, which I believe we currently prevent.

**Comment by apparentlymart** [comment]
> My understanding is that config includes computed-only attributes and sets them as null at validate time, and the framework transforms them to be unknown automatically at plan time. I think this because config and state and plan are always supposed to conform to the schema, and omitting an attribute changes the type completely, so if computed-only attributes were omitted, we wouldn't be able to decode them using their schema types.

This is accurate. The Terraform type system is a structural type system, meaning that a type is defined by its shape rather than by a name, and so we use null values to represent a particular attribute being unset while still keeping the type consistent.

It might be interesting to note that early in the v0.12 development we had Terraform Core automatically setting computed attributes to be unknown in the config before sending to the provider, and that was how we realized the ambiguity between two different situations involving unknown values:

* If the configuration for an argument refers to a computed attribute from another resource, it will appear as unknown.
* If the configuration for a computed argument isn't set at all -- either because it's `Computed` or because it's `Optional`+`Computed` -- it would've also appeared as unknown. (but now it appears as null in this case)

To resolve that ambiguity, we changed the config values in the protocol to represent _just_ what's in the configuration, without further interpretation, and expect the provider to provide the unknown value placeholders in return if needed. That way, provider logic referring to the config value can assume that null always means that the value wasn't set in configuration, and take whatever action is appropriate for that case. (Set it to unknown, set it to some default value, or leave it as null.)

**Comment by paddycarver** [comment]
I was imprecise in my language above, but I think the framework does that, too. The config (which is always surfaced) retains the `null`. The plan upgrades Computed nulls to `unknown`, to save the provider developer from needing to remember to do that on everything. So examining the config gives you what the practitioner actually entered, and the plan works as a reasonable default value for what should be in the plan.

**Comment by apparentlymart** [comment]
In return for your increased precision I will offer my own, for anyone following along here who is accustomed to seeing things from the other side of the SDK/framework abstraction: :grinning:

I should be clear that when I'm talking about what Terraform Core does I tend to use "the provider" and "provider logic" to represent the entire set of code running on the other end of the provider protocol, even though in practice some of that logic of course belongs to the SDK/framework and not to the provider codebase directly. The particular internal architecture of a provider plugin isn't visible to Terraform Core, as long as the result somehow conforms to the protocol.

I suspect my intent was probably already understandable based on the context, but wanted to clarify just in case. A provider written against the framework here won't necessarily need to meet all of Terraform Core's expectations itself.

**Comment by bflad** [comment]
#185 likely resolves the underlying cause of this error. I have added this as a use case in #113. Closing this ambiguous issue in preference of those.
