### ISSUE TITLE
Add SetPath Method to Diagnostic Type

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-framework#169]
### Module version

```
v0.3.0
```

### Use-cases

Certain functionality is purely value-based, meaning it does not have the associated path context of where the value was sourced. For example, `tfsdk.ValueAs(context.Context, attr.Value, interface{})`

In these situations, it may be necessary to enhance any returned diagnostics with known path information so practitioners and provider developers can include known context for easier troubleshooting.

### Attempted Solutions

```go
valueAsDiags := ValueAs(ctx, attrValue, target)

// ValueAs does not have path information for its Diagnostics.
for idx, valueAsDiag := range valueAsDiags {
	if valueAsDiag.Severity() == diag.SeverityError {
		valueAsDiags[idx] = diag.NewAttributeErrorDiagnostic(
			path,
			valueAsDiag.Summary(),
			valueAsDiag.Detail(),
		)
	} else if valueAsDiag.Severity() == diag.SeverityWarning {
		valueAsDiags[idx] = diag.NewAttributeWarningDiagnostic(
			path,
			valueAsDiag.Summary(),
			valueAsDiag.Detail(),
		)
	}
}

diags.Append(valueAsDiags...)
```

### Proposal

Require `SetPath(*tftypes.AttributePath)` method on `diag.Diagnostic` interface type, with required implementations on other `diag` types.

A rough detail here currently is that `DiagnosticWithPath` is its own interface type. It may be worth consolidating that into `Diagnostic` so all implementations can be path aware.

Something potentially worth considering is whether the other core diagnostics data fields such as summary, detail, and severity should _also_ have setter methods, to make diagnostics modifications easier.

### References

- https://github.com/hashicorp/terraform-plugin-framework/pull/167/files#r712367066

**Comment by apparentlymart** [comment]
This problem interested me because it seems like a next-level-down version of a problem we already encountered various times in Terraform Core: the codepath generating the diagnostic knows what's wrong but doesn't have the context to describe _where_ it's wrong.

To address that in Terraform Core we have a kinda funny idea of "contextual diagnostics", where there's an implied agreement between caller and callee that the callee can return an explicitly-incomplete diagnostic and then the caller will later complete it by retroactively adding whatever context the callee didn't have.

The most common example of that for Terraform Core is when a body decoder knows that the problem is at a particular attribute path within its body, but only the caller actually _has_ the body. The provider protocol itself is an example of this: the diagnostics you're trying to return in this issue come back with an attribute path but not the body the attributes belong to, and so Terraform Core retrofits those diagnostics with a body:

1. The provider's diagnostics, with just attribute paths, initially go into [`tfdiags.AttributeValue`](https://pkg.go.dev/github.com/hashicorp/terraform/internal/tfdiags#AttributeValue) thanks to the `tfproto5` and `tfproto6` client code. That codepath only has the `cty.Value` we eventually extracted from the configuration, not the source AST it was constructed from.
2. Further up the call stack, outside of the provider protocol handling, we call [`Diagnostics.InConfigBody`](https://pkg.go.dev/github.com/hashicorp/terraform/internal/tfdiags#Diagnostics.InConfigBody), which looks for specific diagnostics that are body-contextual and replaces them with fully-specified diagnostics that refer to particular source locations in the input.

In your case the problem is the diagnostics might start with relative attribute paths or no attribute paths at all and need the _attribute path_ added as additional context, and so `Diagnostics.InConfigBody` might be `Diagnostics.UnderAttributePath` instead, but I think the overall pattern still adds up here.

Terraform Core does have the advantage that it's always talking to itself: the two steps above both belong to Terraform Core, they are just internal subsystems; if we need to change the contract here, we can change the caller and callee in a single commit and just move on. This might be more risky for an interface that spans across an architectural boundary (SDK and Provider), but I thought I'd draw attention to it anyway in case it gives some ideas.
