### ISSUE TITLE
Computed only attributes present provider bug error when configured.

### ISSUE THREAD

**Issue by iwarapter** [hashicorp/terraform-plugin-framework#276]
### Module version
```
github.com/hashicorp/terraform-plugin-framework v0.6.0
```

### Relevant provider source code

https://github.com/iwarapter/terraform-provider-corner/commit/886c694147ec0548c94f1eb08b9c14d58c8272ba

### Terraform Configuration Files

```hcl
resource "framework_user" "foo" {
  email = "jdoe@example.com"
  name = "J Doe"
  age = 18
  id = "jdoe"
  language = "es"
  date_joined = "break"
}
```

### Expected Behavior

sdkv2 presents an error like so:
```
=== RUN   TestAccTests/corner_user
    provider_test.go:37: Step 1/1 error: Error running pre-apply refresh: exit status 1
        
        Error: Value for unconfigurable attribute
        
          with corner_user.foo,
          on terraform_plugin_test.tf line 6, in resource "corner_user" "foo":
           6:   date_joined = "break"
        
        Can't configure a value for "date_joined": its value will be decided
        automatically based on the result of applying this configuration.
```

### Actual Behavior

Framework errors with provider bug message:
```
=== RUN   TestAccFrameworkResourceUser_language
    resource_user_test.go:39: Step 1/1 error: Error running pre-apply refresh: exit status 1
        
        Error: Provider produced invalid plan
        
        Provider "registry.terraform.io/hashicorp/framework" planned an invalid value
        for framework_user.foo.date_joined: planned value cty.NullVal(cty.String)
        does not match config value cty.StringVal("break").
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
```

### Steps to Reproduce

1. Checkout the corner project fork
2. make testacc

### References

I was unable to see anything similar in the existing issues/discuss topics.

**Comment by bflad** [comment]
Hi @iwarapter 👋  Thank you for raising this and diving a bit into it!

This behavior is certainly not expected, however the reasoning may be a little strange. I believe there have been some assumptions that Terraform CLI automatically performed this type of configuration validation since it already receives the "configurability" of an attribute via the required/optional/computed schema fields. However as you have found, it just so happens that the older provider SDK was the one implementing this validation logic.

I'm double checking with the maintainers of Terraform CLI, however I anticipate that rather than introducing any changes into this project (except potentially adding this validation as a stopgap solution), that we would rectify this upstream so all provider implementations (e.g. terraform-plugin-go and other potential SDKs) do not need to handle this unexpected situation either. I'll provide an upstream issue link or more information once I can.

Thanks again!

**Comment by bflad** [comment]
Created upstream issue: https://github.com/hashicorp/terraform/issues/30669

**Comment by bflad** [comment]
Since there are plenty of Terraform CLI versions without the configuration checking, even if it got implemented today, we will add the checks to the framework as well so the error messaging is clearer.
