### ISSUE TITLE
Cannot load custom provider

### ISSUE THREAD

**Issue by chrispytoes** [hashicorp/terraform-plugin-framework#327]
### Module version
`v0.8.0`

### Relevant provider source code
main.go
```go
providerserver.Serve(context.Background(), NewProvider, providerserver.ServeOpts{
  Address: "registry.terraform.io/example/connectwise",
  Debug:   true,
})
```
provider.go
```go
package main

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"terraform-provider-connectwise/helpers"
	"terraform-provider-connectwise/resources/company"
)

type CWProvider struct {
	ApiKey    string `tfsdk:"api_key"`
	ApiSecret string `tfsdk:"api_secret"`
	ClientId  string `tfsdk:"client_id"`
}

func NewProvider() tfsdk.Provider {
	return &CWProvider{}
}

func (p CWProvider) GetSchema(ctx context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return tfsdk.Schema{
		Attributes: map[string]tfsdk.Attribute{
			"api_key":    helpers.RequiredStringAttr(),
			"api_secret": helpers.RequiredStringAttr(),
			"client_id":  helpers.RequiredStringAttr(),
		},
	}, diag.Diagnostics{}
}

func (p CWProvider) Configure(ctx context.Context, request tfsdk.ConfigureProviderRequest, response *tfsdk.ConfigureProviderResponse) {
	request.Config.Get(ctx, p)
}

func (p CWProvider) GetResources(ctx context.Context) (map[string]tfsdk.ResourceType, diag.Diagnostics) {
	return map[string]tfsdk.ResourceType{
		"configuration": company.ConfigurationResourceType{},
	}, diag.Diagnostics{}
}

func (p CWProvider) GetDataSources(ctx context.Context) (map[string]tfsdk.DataSourceType, diag.Diagnostics) {
	return map[string]tfsdk.DataSourceType{}, diag.Diagnostics{}
}

```

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    connectwise = {
      source = "registry.terraform.io/example/connectwise"
    }
  }
}

provider "connectwise" {
  api_key = "test"
  api_secret = "test"
  client_id = "test"
}

resource "connectwise_configuration" "test" {
  name = "Terraform Test"
  company_id = 22202
}
```

### Debug Output
```
│ Error: Failed to load plugin schemas
│
│ Error while loading schemas for plugin components: Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/example/connectwise: failed to instantiate provider "registry.terraform.io/example/connectwise" to obtain schema: Unrecognized remote plugin message: Provider started. To attach Terraform CLI, set the
│ TF_REATTACH_PROVIDERS environment variable with the following:
│
│ This usually means that the plugin is either invalid or simply
│ needs to be recompiled to support the latest protocol...
```

I'm trying to test my custom Terraform provider after following [this tutorial](https://learn.hashicorp.com/tutorials/terraform/plugin-framework-create?in=terraform/providers) and I'm having trouble getting it to actually run.

I placed a `terraform.rc` file inside `C:\Users\me\Appdata\Roaming` with the following contents:
```
provider_installation {
  dev_overrides {
    "registry.terraform.io/example/connectwise" = "/Users/me/go/bin"
  }

  direct {}
}
```
After installing the provider with `go install` and trying to apply my test config, I get the error above.

**Comment by qiangtang** [comment]
I have hit the similar issue and filed https://github.com/hashicorp/terraform-provider-scaffolding-framework/issues/48 to track this also.

**Comment by chrispytoes** [comment]
@qiangtang Strange, I just tried downgrading to v0.7.0 and switching to the deprecated `tfsdk.Serve` function, but I'm still getting the same error.

**Comment by chrispytoes** [comment]
I fixed it! I didn't realize that the resource names returned by `GetResources` need to include the provider name. I changed `configuration` to `connectwise_configuration` and that fixed it.

Maybe a better error message can be given for this? I was under the impression that the provider name was always automatically appended to the beginning of resource names.

**Comment by iafilius** [comment]
Hi, looks like you set Debug to true, and just dynamic trying to load the module. 
For dynamic loading you need to set Debug to False, and if you want it to debug with debugger, you may want to set debug to true. Had of course the same error output after  setting debug to true, not knowing it needed special purpose/treatment. For that Debug=true and not able to load schema  error message i would recommend a more clear error message. at least i didn't see relation with debug = true right away

**Comment by bflad** [comment]
Thanks for the followup, @chrispytoes! I have submitted https://github.com/hashicorp/terraform-plugin-framework/pull/379 to include that convention in the Go documentation for the methods. It looks like it was offhandedly mentioned in the website documentation as well at https://www.terraform.io/plugin/framework/providers#getresources. If there are other ways you believe we could improve the documentation, we can certainly explore those as well.

To try and prevent this, the framework could try these, but they each introduce their own complications which I think are worth more discussion before any sort of potential implementation:

- Automatically appending the provider name to data source and resource names: Given this naming convention is not a requirement, this would prevent valid use cases. For example, there are the `external` and `http` data sources. There are also existing providers where all resource names do not use the provider name and configurations rely on `provider = ` meta-argument, such as a private providers that deploy tailored versions of infrastructure.
- Implementing provider validation as unit testing with this convention hard requirement (#113): Suffers from similar problems to above as we wouldn't want to prevent those use cases from having this type of validation.
- Implementing provider validation as unit testing with this convention as a soft requirement or a separate unit testing setup for "style" checks (#113): Likely best discussed in that separate issue.

As for the error messaging here, it is coming from Terraform CLI, which only has a generic worldview of the potential issue. It does not know when given binaries are providers that are implemented using this framework, for example. I will open an issue [in that issue tracker](https://github.com/hashicorp/terraform/issues) to potentially adjust the messaging though, since there may be room to provide additional suggestions for provider developers.
