### ISSUE TITLE
API for passing env variables from tf CLI to providers, to aid provider reattach

### ISSUE THREAD

**Issue by PJB3005** [hashicorp/terraform-plugin-framework#448]
### Module version

```
v0.10.0
```

### Use-cases
Right now it seems that one of the recommended ways to pass API keys to providers is by using environment variables[^1]. This generally works fine because in most cases Terraform loads the provider plug-ins itself (and thus they inherit the environment). It breaks down however when you run the provider in debugger mode, in which case the environment is different.

This is *really* annoying to me while testing, because I now have to replicate my API key env vars into my debug launch configuration. Ideally Terraform would have some way of passing these variables over to the provider so that the provider works the same whether reattached or not.

I've seen that [proposals to have an `env()` function in HCL](https://github.com/hashicorp/terraform/issues/15440) were rejected, which would also have been a solution to this problem. Like one of the commenters however I agree that the reasoning is flawed since providers still pull env vars themselves. 

### Attempted Solutions
None

### Proposal
The easiest approach I can think of is to make `ConfigureProviderRequest` contain a `map[string]string` of the terraform CLI env variables, or a more nuanced type like that. Then providers can just pull from that instead of using `os.Getenv()`.

### References
- https://github.com/hashicorp/terraform/issues/15440

[^1]: https://github.com/hashicorp/terraform-provider-hashicups-pf/blob/3ec094b2a5ff4f0c1c1e6f6de4fd16ef2313b936/hashicups/provider.go#L102

**Comment by bflad** [comment]
Hi @PJB3005 👋 Thank you for raising this feature request. I can certainly see how this might be frustrating in some regards.

To provide some initial thoughts and insight into this type of change:

Many providers opt to allow this type of provider configuration via environment variables and with Terraform configuration via a provider schema implementation, where the Terraform configuration value takes precedence over any environment variable value. This enables usage of Terraform details such as [`TF_VAR_*` environment variables](https://www.terraform.io/language/values/variables#environment-variables) or [`*.tfvars` files](https://www.terraform.io/language/values/variables#variable-definitions-tfvars-files), although that may also be awkward to implement in the provider debugging scenario since it requires setting up configurations a certain way or wrapping the debug execution in a special script rather than just starting the provider binary. That may be the best recommendation for now though, given the current experience.

In order for providers to receive this type of information from Terraform, it must be implemented in the [Terraform Plugin Protocol](https://www.terraform.io/plugin/how-terraform-works#terraform-plugin-protocol) and then Terraform itself. Terraform's current development model is that changes may only be backported one minor version (e.g. as of today, Terraform development is on 1.3 and backports are only to 1.2). Therefore this functionality, even if implemented in the protocol right now, would not be accessible during all supported versions of Terraform by the framework. Providers would then need to fallback to checking the process environment variables as they do today to ensure proper configuration. This implementation detail might be confusing to provider developers.

It may be worth raising this upstream though, just to see if there are any new thoughts or insights on this from their perspective. Provider debugging support (where the processes are started in reverse order) is relatively newer compared to those older upstream GitHub issues. Ultimately, they would need to accept this sort of change as well, so their decision would influence what can be done here.

To be transparent on this side, the team developing the framework is hard at work on finalizing an initial v1 major version release with compatibility promises, therefore there is a prioritization of potentially breaking changes at the moment over changes which can be implemented without compatibility concerns later on. This may delay further maintainer discussions and efforts with this type of enhancement since it likely can be done without breaking anything as proposed.

Thanks again for bringing this up.
