### ISSUE TITLE
Incorrect value provided for request.ProviderData in resource Configure call when Debug is true in providerserver.ServeOpts

### ISSUE THREAD

**Issue by mbartel-sol** [hashicorp/terraform-plugin-framework#490]
### Module version
```
v0.13.0
```

### Relevant provider source code
The `main.go` file implementing the provider:
```go
package main

import (
	"context"
	"flag"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/providerserver"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"log"
)

type apple struct {
	color string
}

func (a *apple) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	a.color, _ = request.ProviderData.(string)
}

func (a apple) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_apple"
}

func (a apple) GetSchema(ctx context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return tfsdk.Schema{
		Attributes: map[string]tfsdk.Attribute{
			"name": {Type: types.StringType, Required: true},
		},
	}, nil
}

func (a apple) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	response.State.Raw = request.Plan.Raw
	response.Private.SetKey(ctx, "color", []byte(`"`+a.color+`"`))
}

func (a apple) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
}

func (a apple) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
}

func (a apple) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
}

type aliasBugProvider struct{}

func (a aliasBugProvider) Metadata(ctx context.Context, request provider.MetadataRequest, response *provider.MetadataResponse) {
	response.TypeName = "example"
}

func (a aliasBugProvider) GetSchema(ctx context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return tfsdk.Schema{
		Attributes: map[string]tfsdk.Attribute{
			"color": {Type: types.StringType, Required: true},
		},
	}, nil
}

func (a aliasBugProvider) Configure(ctx context.Context, request provider.ConfigureRequest, response *provider.ConfigureResponse) {
	var color string
	request.Config.GetAttribute(ctx, path.Root("color"), &color)
	response.ResourceData = color
}

func (a aliasBugProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return nil
}

func (a aliasBugProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		func() resource.Resource {
			return &apple{}
		},
	}
}

func main() {
	debug := flag.Bool("debug", false, "set to true to run the provider with support for debuggers like delve")
	flag.Parse()
	err := providerserver.Serve(context.Background(), func() provider.Provider {
		return &aliasBugProvider{}
	}, providerserver.ServeOpts{Address: "registry.terraform.io/example/alias-bug", Debug: *debug})
	if err != nil {
		log.Fatal(err.Error())
	}
}
```

### Terraform Configuration Files
The Terraform configuration file `test.tf`:
```hcl
terraform {
  required_providers {
    example = {
      source = "example/alias-bug"
    }
  }
}

provider "example" {
  color = "red"
}

provider "example" {
  alias = "alternate"
  color = "green"
}

resource "example_apple" "ant" {
  name = "Fire"
}

resource "example_apple" "bat" {
  provider = example.alternate
  name = "Wom"
}
```
The local provider configuration `test.tfrc` (for running the non-debug circumstance in
which it works correctly):
```hcl
provider_installation {
	dev_overrides {
		"example/alias-bug" = "build"
	}
	direct {}
}
```

### Expected Behavior
For the instances of the resources on which `Create` is called, the `ant` resource
should have `color`==`red` in `request.ProviderData` in the
`Configure` call and the `bat` resource should have `color`==`green` in
`request.ProviderData` in the `Configure` call, resulting in the corresponding values
ending up in the `private` `terraform.tfstate` property for each resource.

### Actual Behavior
For the instances of the resources on which `Create` is called, both the `ant` resource
and the `bat` resource are configured with the same `color` value in
`request.ProviderData` in the `Configure` call, resulting in one of the resources having incorrect
configuration during `Create`.  When running the test this behaviour results in the `private`
`terraform.tfstate` property for the instances being identical.  Which configuration is
provided during the Configure call seems to be random, but both resources always
receive the same configuration instead of different configuration as they should.

I'll note that in my tests 14 instances of the resource were created and some
receive one configuration and some the other.  However, the two instances that
are actually used in `Create` calls always receive the same configuration.
I'll also note that the `provider` property for the resources in `terraform.tfstate`
is correct.

### Steps to Reproduce
1. In a terminal window, create a directory to contain the test files:
   ```
   mkdir terraform-provider-alias-bug
   cd terraform-provider-alias-bug
   ```
2. Create the `main.go`, `test.tf`, and `test.tfrc` files in the directory.
3. Create the Go module and set up the dependencies:
   ```
   go mod init alias-bug
   go mod tidy
   ```
4. Build the provider:
   ```
   go build -o build/terraform-provider-alias-bug
   ```
5. Run the provider in debug mode:
   ```
   build/terraform-provider-alias-bug -debug
   ```
6. Copy the `TF_REATTACH_PROVIDERS` line from the provider output.
7. Open a new terminal window and navigate to the same directory.
8. Set the `TF_REATTACH_PROVIDERS` environment variable in the new window from the copy step above.
   ```
   export TF_REATTACH_PROVIDERS=...
   ```
9. Apply the test configuration:
   ```
   terraform apply -auto-approve
   ```
10. Inspect `terraform.tfstate` and note that the `private` data is incorrectly the same for both resources:
    ```json
    {
      "version": 4,
      "terraform_version": "1.2.9",
      "serial": 3,
      "lineage": "35ec60ef-ec32-5a8e-7cf2-4418accba28d",
      "outputs": {},
      "resources": [
        {
          "mode": "managed",
          "type": "example_apple",
          "name": "ant",
          "provider": "provider[\"registry.terraform.io/example/alias-bug\"]",
          "instances": [
            {
              "schema_version": 0,
              "attributes": {
                "name": "Fire"
              },
              "sensitive_attributes": [],
              "private": "eyJjb2xvciI6IkluSmxaQ0k9In0="
            }
          ]
        },
        {
          "mode": "managed",
          "type": "example_apple",
          "name": "bat",
          "provider": "provider[\"registry.terraform.io/example/alias-bug\"].alternate",
          "instances": [
            {
              "schema_version": 0,
              "attributes": {
                "name": "Wom"
              },
              "sensitive_attributes": [],
              "private": "eyJjb2xvciI6IkluSmxaQ0k9In0="
            }
          ]
        }
      ]
    }
    ```
11. For the correct result, apply the config in non-debug mode:
    ```
    rm terraform.tfstate
    unset TF_REATTACH_PROVIDERS
    export TF_CLI_CONFIG_FILE=test.tfrc
    terraform apply -auto-approve
    ```
12. Observe the correct `private` data in `terraform.tfstate`:
    ```json
    {
      "version": 4,
      "terraform_version": "1.2.9",
      "serial": 3,
      "lineage": "87fa87a0-f9a0-9e2d-76da-a7f6242ca684",
      "outputs": {},
      "resources": [
        {
          "mode": "managed",
          "type": "example_apple",
          "name": "ant",
          "provider": "provider[\"registry.terraform.io/example/alias-bug\"]",
          "instances": [
            {
              "schema_version": 0,
              "attributes": {
                "name": "Fire"
              },
              "sensitive_attributes": [],
              "private": "eyJjb2xvciI6IkluSmxaQ0k9In0="
            }
          ]
        },
        {
          "mode": "managed",
          "type": "example_apple",
          "name": "bat",
          "provider": "provider[\"registry.terraform.io/example/alias-bug\"].alternate",
          "instances": [
            {
              "schema_version": 0,
              "attributes": {
                "name": "Wom"
              },
              "sensitive_attributes": [],
              "private": "eyJjb2xvciI6IkltZHlaV1Z1SWc9PSJ9"
            }
          ]
        }
      ]
    }
    ```

**Comment by bflad** [comment]
Hi @mbartel-sol 👋 Thank you for raising this and sorry you ran into trouble here.

Normally when Terraform interacts with a provider while executing a command, it spins up individual provider processes per-alias (otherwise called a provider instance) and shuts down the provider processes between commands. In this case, each provider instance receives its own `ConfigureProvider` RPC and therefore there is no shared process memory between them.

When you run a provider in debugging mode, it becomes a singular, long-running process. From Terraform's perspective, there is a single reattachment address for all provider instances with the same provider address (e.g. `registry.terraform.io/example/alias-bug`), so Terraform will make all the normal RPCs against that single provider process. In this case, the process will receive the multiple, but differing `ConfigureProvider` RPCs, which can occur at different times depending on how the graph is constructed and how nodes are executed concurrently. If you run Terraform with TRACE logging enabled, e.g. `TF_LOG=TRACE terraform apply`, the log output should show multiple `ConfigureProvider` RPCs being handled.

The provider debugging feature was originally designed for debugging a single provider process, or put differently in this context, a single provider instance/alias. Terraform only supports a single process per provider address currently. It would require some redesign to support multiple instances/aliases for debugging. You would need to spin up providers with differing provider addresses and expose those multiple addresses in the reattachment configuration to workaround the current design.

I hope this clarifies a little about what is likely happening here, although I do understand it might not be desirable for this particular usage. Unfortunately, I'm not sure there's much we can do within the framework in this case. We cannot raise errors if a provider receives multiple `ConfigureProvider` RPCs, since there are valid cases for that behavior when debugging. As a provider developer, you can implement your own logic, such as implementing `sync.Once` to prevent differing provider configurations when `ConfigureProvider` is called multiple times although that certainly would not work in this particular debugging use case since it appears you explicitly want differing configurations.

As a next step if you want to explore this as more of a feature request to support multiple provider instances with reattachment, would be to open a [GitHub issue upstream](https://github.com/hashicorp/terraform/issues) to see if those maintainers have any thoughts here. Maybe they can search reattach addresses by provider address + alias first, then fall back to the current behavior of just the provider address.

**Comment by mbartel-sol** [comment]
The process-per-provider-instance design choice is reasonable.  It would be good to document that debugging simply won't work with provider aliases in [the debugging documentation](https://www.terraform.io/plugin/debugging#enabling-debugging-in-a-provider), specifically in the place where it talks about differences (it mentions it is one process versus several, but not the ramifications of that).  The implication of

> its behavior will change in minor ways from normal operation of providers

is that while the way that terraform interacts with the provider might change in debugging mode, for a well-written provider any config should still work just fine, including complex configurations.
