### ISSUE TITLE
Modifiers seem to get ignored for Provider Schemas

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [hashicorp/terraform-plugin-framework#492]
### Module version

```
github.com/hashicorp/terraform-plugin-framework v0.13.0
```

### Relevant provider source code

```go
			"timeout": {
				Type:                types.Int64Type,
				MarkdownDescription: "timeout backend connection after value seconds (default: `5`)",
				Optional:            true,
				Computed:            true,
				PlanModifiers: tfsdk.AttributePlanModifiers{
					planmodifiers.IntDefaultModifier(5), # Modify function immediately would panic
					resource.UseStateForUnknown(),
				},
			},
```

### Terraform Configuration Files

```hcl
resource "foo" "bar" {
# no timeout set
}
```

### Expected Behavior
Panic
It should first run Modifiers and afterwards call provider.Configure.
Alternatively it should complain that Modifiers are not supported in ProviderSchemas.

### Actual Behavior
No panic
It does not seem to run the Modifiers at all.

**Comment by bflad** [comment]
Hi @AndreasBergmeier6176 👋 

Plan modification only applies to resources, not data sources or providers, since the latter two do not actually have an equivalent "planning" phase in Terraform. The [`tfsdk.Attribute` type `PlanModifiers` field](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/tfsdk#Attribute.PlanModifiers) currently tries to provide this hint:

> 	// Plan modification only applies to resources, not data sources or
	// providers. Setting PlanModifiers on a data source or provider attribute
	// will have no effect.

However, it is certainly understandable that this is possible to miss in the Go documentation and given there is no compiler feedback about the issue. We currently plan on (at least) splitting up `tfsdk.Attribute` so there are `datasource`, `provider`, and `resource` package specific types with only the features supported by those concepts. In this case, the provider attribute would omit the `PlanModifiers` field. Some of that effort is being offhandedly tracked in #365, although this would be a good succinct issue to capture this particular development issue.

To implement the same logic of the provider attribute plan modifiers, it can be baked into the provider `Configure` method for now.

**Comment by bflad** [comment]
Ah, it turns out that there was already an open issue for making this compiler-time feedback: https://github.com/hashicorp/terraform-plugin-framework/issues/132

To consolidate discussions and efforts on this topic, I'm going to close this issue in preference of the existing one. 👍
