### ISSUE TITLE
Support Validation For Unique Keys in schema.MapNestedAttribute

### ISSUE THREAD

**Issue by jaloren** [hashicorp/terraform-plugin-framework#581]
### Module version
```
github.com/hashicorp/terraform-plugin-framework v0.17.0
```

### Use-cases

I have a resource schema with MapNestedAttribute like so. I want to ensure that the attribute does not have duplicate keys. If there are, I want the plan to fail. I have been unable to find any mechanism to do that because by the time validator is invoked, the keys have been loaded into a map which means the last duplicate key overwrote all preceding dups. 

```
	"columns": schema.MapNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: ....,
				},
				Required: true,
				Validators: []validator.Map{
					&columnValidator{},
				},
			},
```

https://github.com/hashicorp/terraform/issues/28727

### Attempted Solutions

I tried:

- implementing a validator.Map
- creating a CustomType which implements types.MapTypable

Note there might be a way to do this with a custom type and this could be solved with some docs.

### References
- https://github.com/hashicorp/terraform/issues/28727

**Comment by bflad** [comment]
Hi @jaloren 👋 Thank you for raising this. We'll need to double check what is possible on the provider-side of the Terraform protocol here as we may only receive the deduplicated map from Terraform core after it parses the configuration. In that case, any enhancement here would need to happen over there.

**Comment by jaloren** [comment]
@bflad yes, i was afraid you were going to say that :).  I found these issues which look like the root of the issue. 

https://github.com/hashicorp/hcl/issues/35
https://github.com/hashicorp/terraform/issues/28727

**Comment by bflad** [comment]
After looking into this a little further, my understanding is that the protocol representation of map-based data will already have "deduplicated" keys due to Terraform's underlying map value storage ([`cty,Map`](https://github.com/zclconf/go-cty/blob/main/docs/types.md#ctymap-types)) before its submitted across the protocol. Since I do not believe we can do anything on our side of the protocol for this within terraform-plugin-go or terraform-plugin-framework, I'm going to close this so we can track actionable issues for this project's maintainers. I'd suggest 👍 reacting and subscribing/commenting to those issues upstream for further updates.
