### ISSUE TITLE
Float64 Type Validation Error (123 and 123.5 work, but 123.2 fails)

### ISSUE THREAD

**Issue by RobM83** [hashicorp/terraform-plugin-framework#613]
I'm trying to write my own provider with the plugin framework, but the validation on `schema.Float64Attribute` fails.

### Module version

```
github.com/hashicorp/terraform-plugin-framework v1.0.1
```

### Relevant provider source code

```go
"latitude": schema.Float64Attribute{
	Description:         "Latitude of the resource location",
	MarkdownDescription: "Latitude of the resource location",
	Optional:            true,
},
```

### Terraform Configuration Files

```hcl
latitude  = "123.2"
```

### Expected Behavior

The expected result should be, that floating point numbers like latitude and longitude in this case should be accepted.

### Actual Behavior

Terraform validation fails, when I try to set a value, which is not a “whole” number or a float ending with “.5” So these numbers work (123, 123.5), but all other numbers like (123.1, 123.2, etc.) fail. 

Error message:
```
Float64 Type Validation Error: Value %!s(*big.Float=123.6) cannot be represented as a 64-bit floating point.
```

### References

I posted this on the Hashicorp discuss forum as well: 
https://discuss.hashicorp.com/t/terraform-plugin-framework-float64-type-validation-error/48645

**Comment by bflad** [comment]
I have confirmed this as a bug in the framework implementation. `Float64Type` implements a `Validate` method, which calls [`(*big.Float).Float64()`](https://pkg.go.dev/math/big#Float.Float64) and uses the accuracy return to return the error. The problem here is that Terraform can encode this number using string formatting (valid in the protocol), then when upstream terraform-plugin-go decodes that string it is using `big.ParseFloat(rv, 10, 512, big.ToNearestEven)` which can set the accuracy not equal to exact, which that (in)accuracy is then returned by the `Float64()` method during the validation.

A course of action here for `Float64Type` is likely to switch the `Validate` method logic to perform value checks mentioned in the `Float64()`  Go documentation instead of solely checking the `big.Accuracy` return:

>  If x is too small to be represented by a float64 (|x| < math.SmallestNonzeroFloat64), the result is (0, Below) or (-0, Above), respectively, depending on the sign of x. If x is too large to be represented by a float64 (|x| > math.MaxFloat64), the result is (+Inf, Above) or (-Inf, Below), depending on the sign of x.

`Int64Type` has similar validation, but the `Int64()` method documentation mentions the accuracy is safe to use in this manner:

> If math.MinInt64 <= x <= math.MaxInt64, the result is Exact if x is an integer, and Above (x < 0) or Below (x > 0) otherwise. The result is (math.MinInt64, Above) for x < math.MinInt64, and (math.MaxInt64, Below) for x > math.MaxInt64.
