### ISSUE TITLE
Allow easier testing of resource's disappearance

### ISSUE THREAD

**Issue by pecigonzalo** [hashicorp/terraform-plugin-framework#617]
Since this way of creating plugins is the preferred one and `terraform-plugin-sdk` is not, I want to just cross-reference this, as I believe its an important missing feature.

### References

https://github.com/hashicorp/terraform-plugin-sdk/issues/236

**Comment by bflad** [comment]
Hi @pecigonzalo 👋 Thank you for raising this here. Are you looking for framework specific code to help in this case? If so, could you share some of your thoughts?

**Comment by pecigonzalo** [comment]
Hey @bflad, yes, ideally the framework would have some helper function or step that allows for testing that given a resource is missing, `terraform plan` correctly handles it. Correctly defined by the user.
A "kind" of `TestCase` (or flag) that injects an arbitrary resource into the state (that is not in the backing service), which then plan/apply tests should handle.

Maybe there is an ergonomic way to do this already, but by looking at the linked issue there does not seem to be one.

**Comment by bflad** [comment]
The provider testing code (e.g. github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource package) is a wrapper for various Terraform CLI executions to simulate a full resource lifecycle. It is currently agnostic to the actual provider code implementations beyond the provider server entry points so providers can be managed (started/stopped) by the testing code. Implementing SDK-specific functionality into the testing code itself would be a design change. I mention this because unless there's something that _cannot_ be done with standard Terraform configurations and command executions, it gets harder to justify more tightly coupling the testing code to the various SDKs.

To throw a proposal out there involving no coupling to a specific SDK, one could imagine having a test step which handles the equivalent of calling `terraform destroy -target=examplecloud_thing.test`, but also offering the option to preserve the prior state. This means Terraform will call the provider code's "Delete" functionality without needing the details of the underlying provider implementation/SDK. From a usage perspective, it could look something like:

```go
resource.TestCase{
  // ... other fields
  Steps: []resource.TestStep{
    // Create our resource and state for disappearance testing.
    {
      Config: `resource "examplecloud_thing" "test" {}`,
    },
    // Design sketch -- the example Targets and PreservePriorState fields do not exist today.
    // Targets would allow a complex configuration to test only the desired resource.
    // PreservePriorState would keep the existing Terraform state from the prior step.
    {
      Config: `resource "examplecloud_thing" "test" {}`,
      Destroy: true,
      Targets: []string{"examplecloud_thing.test"},
      PreservePriorState: true,
    },
    // Verify refresh behavior for now-missing resource.
    {
      Config: `resource "examplecloud_thing" "test" {}`,
      PlanOnly: true, // or RefreshState: true
    },
  },
}
```

Or it could be made into it's own "TestStep mode" to combine the latter two steps. This is an implementation detail more suited for discussion over in the original issue though.

Would something like this satisfy what you are looking for?

**Comment by pecigonzalo** [comment]
Amazing idea @bflad, that sounds quite reasonable, portable and provider agnostic. I'm not familiar with the provider testing codebase (ill take a deeper look later) but it also seems like a relatively simple solution, as we just need to keep a copy of the old state.

**Comment by bflad** [comment]
In that case, I'm going to close this issue in preference of the existing https://github.com/hashicorp/terraform-plugin-sdk/issues/236 (already commented with the same proposal) to consolidate discussions and since there would be nothing actionable for this codebase. Thanks again for bringing this up.
