### ISSUE TITLE
`computed` field producing spurious plan changes with framework but not SDK v2

### ISSUE THREAD

**Issue by asaba-hashi** [hashicorp/terraform-plugin-framework#628]
### Module version

```
github.com/hashicorp/terraform-plugin-framework v1.0.1
```

### Relevant provider source code

PR for updating the provider to framework: https://github.com/JupiterOne/terraform-provider-jupiterone/pull/136/files#diff-516571d421fdf72766d23e79357696f48d9949132cfd700d30df5a26fa0dc8aa

These errors are occurred in the tests when moving from SDK v2 to Framework:

Framework:
```go
		        "version": schema.Int64Attribute{
				Description: "Computed current version of the rule. Incremented each time the rule is updated.",
				Computed:    true,
			},
```

SDK:
```go
			"version": {
				Type:        schema.TypeInt,
				Description: "Computed current version of the rule. Incremented each time the rule is updated.",
				Computed:    true,
			},
```

### Terraform Configuration Files

This happens as part of the acceptance tests.

```go
func TestRuleInstance_Basic(t *testing.T) {
	ctx := context.TODO()

	recorder, cleanup := setupCassettes(t.Name())
	defer cleanup(t)
	testHttpClient := cleanhttp.DefaultClient()
	testHttpClient.Transport = logging.NewTransport("JupiterOne", recorder)
	// testJ1Client is used for direct calls for CheckDestroy/etc.
	testJ1Client, err := (&JupiterOneProviderModel{httpClient: testHttpClient}).Client(ctx)
	if err != nil {
		t.Fatal("error configuring check client", err)
	}

	ruleName := "tf-provider-rule"
	resourceName := "jupiterone_rule.test"
	operations := getValidOperations()
	operationsUpdate := getValidOperationsWithoutConditions()
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories(testJ1Client),
		CheckDestroy:             testAccCheckRuleInstanceDestroy(ctx, resourceName, testJ1Client),
		Steps: []resource.TestStep{
			{
				Config: testRuleInstanceBasicConfigWithOperations(ruleName, operations),
				Check: resource.ComposeTestCheckFunc(
				),
			},
			{
				Config: testRuleInstanceBasicConfigWithOperations(ruleName, operationsUpdate),
				Check: resource.ComposeTestCheckFunc(
				),
			},
		},
	})
}

func testRuleInstanceBasicConfigWithOperations(rName string, operations string) string {
	return fmt.Sprintf(`
		resource "jupiterone_rule" "test" {
			name = %q
			description = "Test"
			spec_version = 1
			polling_interval = "ONE_WEEK"
			tags = ["tag1","tag2"]

			question {
				queries {
					name = "query0"
					query = "Find DataStore with classification=('critical' or 'sensitive' or 'confidential' or 'restricted') and encrypted!=true"
					version = "v1"
				}
			}

			outputs = [
				"queries.query0.total",
				"alertLevel"
			]

			operations = %q
		}
	`, rName, operations)
}
```

### Debug Output

https://gist.github.com/asaba-hashi/275dd1d9fc6f774a2ae5629143acde30

### Expected Behavior

The tests should have passed because no changes were detected in the plan for just the computed field.

### Actual Behavior

The test failed with:

```shell
=== RUN   TestRuleInstance_Basic
    resource_rule_test.go:36: Step 1/2 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # jupiterone_rule.test will be updated in-place
          ~ resource "jupiterone_rule" "test" {
                id               = "f2ad0219-549e-4f36-9569-35f8979c38fa"
                name             = "tf-provider-rule"
                tags             = [
                    "tag1",
                    "tag2",
                ]
              ~ version          = 1 -> (known after apply)
                # (5 unchanged attributes hidden)
        
                # (1 unchanged block hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
```

Adding `UseStateForUnknown()` produces the following error:
```
			"version": schema.Int64Attribute{
				Description: "Computed current version of the rule. Incremented each time the rule is updated.",
				Computed:    true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
```

```
=== RUN   TestRuleInstance_Basic
    resource_rule_test.go:36: Step 2/2 error: Error running apply: exit status 1
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to jupiterone_rule.test, provider
        "provider[\"registry.terraform.io/hashicorp/jupiterone\"]" produced an
        unexpected new value: .version: was cty.NumberIntVal(1), but now
        cty.NumberIntVal(2).
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
--- FAIL: TestRuleInstance_Basic (2.08s)
```

A full workaround can be implemented by providing a `ModifyPlan()` that will run after the field plan modifier:
```
// ModifyPlan is a workaround for unexpected behavior in the framework around
// the `computed: true` `version` field to make sure that it is only part of
// the plan if there is some other change in the resource.
//
// Based on the implementation of the Time resource:
// https://github.com/hashicorp/terraform-provider-time/blob/main/internal/provider/resource_time_rotating.go#L189-L234
func (*QuestionRuleResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	// Plan does not need to be modified when the resource is being destroyed.
	if req.Plan.Raw.IsNull() {
		return
	}

	// Plan only needs modifying if the resource already exists as the purpose of
	// the plan modifier is to show updated attribute values on CLI.
	if req.State.Raw.IsNull() {
		return
	}

	var plan, state *RuleModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	if !reflect.DeepEqual(plan, state) {
		resp.Diagnostics.Append(resp.Plan.SetAttribute(ctx, path.Root("version"),
			types.Int64Unknown())...)
	}
}
```

### Steps to Reproduce

1. Remove or comment out the workaround:
   1. `(*RuleResource) ModifyPlan()`
   2. `UseStateForUnknown` on the `version` field schema
3. `make test`.

**Comment by bflad** [comment]
Thank you so much for filing this detailed bug report, @asaba-hashi. I'm going to look into this particular case further, hopefully in the context of also implementing #627.

**Comment by bflad** [comment]
While trying out #627 logging, it looks like the `operations` attribute may be the culprit that is causing the framework to mark the plan with unknowns:

```
2023-01-19T19:19:08.333-0500 [DEBUG] sdk.framework: Detected value change between proposed new state and prior state: tf_req_id=47953e38-cd0b-1585-0b8a-dc7aa420caa3 tf_provider_addr=registry.terraform.io/hashicorp/jupiterone tf_rpc=PlanResourceChange tf_resource_type=jupiterone_rule tf_attribute_path=operations
2023-01-19T19:19:08.333-0500 [DEBUG] sdk.framework: Marking Computed attributes with null configuration values as unknown (known after apply) in the plan to prevent potential Terraform errors: tf_req_id=47953e38-cd0b-1585-0b8a-dc7aa420caa3 tf_provider_addr=registry.terraform.io/hashicorp/jupiterone tf_rpc=PlanResourceChange tf_resource_type=jupiterone_rule
```

Here's the schema from the time I pulled down the code:

```go
			"operations": schema.StringAttribute{
				Description: "Actions that are executed when a corresponding condition is met.",
				Required:    true,
				// PlanModifiers currently tries to diff the json objects and
				// ignore formatting changes, but long term should probably
				// be a TODO for a more complete schema and encouraging
				// jsonencode() usage instead.
				PlanModifiers: []planmodifier.String{
					jsonIgnoreDiffPlanModifier(),
				},
				// TODO: similar to above, longer term is to define more of the
				// schema for HCL and encourage use of jsonencode()
				// Alternative: Look for a JSONString CustomType that comes
				// with it's own validation in it's marshalling
				Validators: []validator.String{
					jsonValidator{},
				},
			},
```

I'm suspecting that it may be JSON string normalization that may be causing the issue in this case. I believe the current plan modification workaround you are using is the best solution for now. Schema-based plan modification can potentially be randomized and it only runs once per attribute. Resource-based plan modification (`ModifyPlan` method) always runs afterward schema-based plan modification so it'll be guaranteed to be "fixed" by then, assuming the JSON normalization is correctly implemented.

---

Over in #627, it outlines the framework's current planning logic. In particular, all provider-defined logic runs after the framework's automatic unknown marking. #183 would be the tracking issue for potentially running schema and resource plan modification logic. It is marked as a breaking change since arbitrarily running the same logic means the logic could receive differing inputs depending on if its before or after the framework's unknown marking. We would not want to force that type of uncertainty into existing or future provider code without signaling it with a major version change.

Rather than #183 though, this general issue could potentially go away with two _targeted_ framework enhancements to accomplish very specific provider needs that could (or maybe _should_) run before the framework compares Terraform's proposed new state and prior state values:

- #70 would be an enhancement so custom types can signal _semantic_ equality between two values. In this case, there would be a JSON string custom type (potentially provided by HashiCorp in the future) that would implement the JSON normalization ("ignore difference") logic. The framework could determine that the proposed new state and prior state JSON strings are actually "equivalent" and adjust the proposed new state to match the prior state in this case, hence removing the difference.
- Native "default value" functionality. While this does not appear to be an issue in this particular situation, we have seen cases where its _significant_ that the proposed new state be adjusted with default values prior to comparing it with the prior state.

**Comment by bflad** [comment]
This should be covered by #737, which will release with v1.3.0 soon. The https://developer.hashicorp.com/terraform/plugin/framework/handling-data/custom-types documentation page releasing with v1.3.0 will be revamped to cover how to set up a custom type with the logic to automatically handle situations like these. 👍
