### ISSUE TITLE
ConfigValidator with nested field works correctly for plan and apply, but not validate

### ISSUE THREAD

**Issue by erademacher** [hashicorp/terraform-plugin-framework#636]
### Module version

```
github.com/hashicorp/terraform-plugin-framework v1.1.1
```

### Relevant provider source code

```go
// in Schema
// ...
"machine_type": schema.StringAttribute{
	Optional: true,
	Computed: true,
},
"num_virtual_cpus": schema.Int64Attribute{
	Optional: true,
	Computed: true,
},
// ...

func (r *clusterResource) ConfigValidators(_ context.Context) []resource.ConfigValidator {
	return []resource.ConfigValidator{
		resourcevalidator.Conflicting(
			path.MatchRoot("dedicated").AtName("num_virtual_cpus"),
			path.MatchRoot("dedicated").AtName("machine_type"),
		),
	}
}
```

### Terraform Configuration Files

```hcl
  dedicated = {
    storage_gib  = var.storage_gib
	machine_type = var.machine_type
    num_virtual_cpus = var.vcpus
  }
```
```hcl
machine_type = "m5.large"
vcpus               = 4
```

### Expected Behavior
`terraform validate` returns an error because both `dedicated.machine_type` and `dedicated.num_virtual_cpus` are configured.

### Actual Behavior
`terraform validate` succeeds, but `terraform plan` and `terraform apply` fail with the expected validation error.

### Steps to Reproduce
1. `terraform validate`

**Comment by erademacher** [comment]
For `terraform validate`, in `ConflictingValidator.Validate`, `machine_type`'s value is `UnknownValue`, even though it's definitely set.

```
configvalidator.ConflictingValidator.Validate (conflicting.go:62) github.com/hashicorp/terraform-plugin-framework-validators/internal/configvalidator
configvalidator.ConflictingValidator.ValidateResource (conflicting.go:43) github.com/hashicorp/terraform-plugin-framework-validators/internal/configvalidator
<autogenerated>:2
fwserver.(*Server).ValidateResourceConfig (server_validateresourceconfig.go:69) github.com/hashicorp/terraform-plugin-framework/internal/fwserver
proto6server.(*Server).ValidateResourceConfig (server_validateresourceconfig.go:44) github.com/hashicorp/terraform-plugin-framework/internal/proto6server
tf6server.(*server).ValidateResourceConfig (server.go:686) github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server
tfplugin6._Provider_ValidateResourceConfig_Handler (tfplugin6_grpc.pb.go:277) github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6
grpc.(*Server).processUnaryRPC (server.go:1340) google.golang.org/grpc
grpc.(*Server).handleStream (server.go:1713) google.golang.org/grpc
grpc.(*Server).serveStreams.func1.2 (server.go:965) google.golang.org/grpc
runtime.goexit (asm_amd64.s:1594) runtime
 - Async Stack Trace
grpc.(*Server).serveStreams.func1 (server.go:963) google.golang.org/grpc
```

For `terraform plan` and `terraform apply`, it makes two passes through `Validate`. The first one exhibits the same issue, but in the second pass, `machine_type` is known and set to the expected value. That's where the validation fails. Both passes have an identical stack trace to the one from `terraform validate`.

**Comment by bflad** [comment]
Hi @erademacher 👋 Thank you for raising this issue and apologies for the confusing behavior. I was able to replicate what you were seeing here, where `terraform validate` seemingly cannot handle validating attributes involving variable definitions, while `terraform plan` does.

While `terraform validate` is generally intended to perform configuration validation, its documentation does note some caveats: https://developer.hashicorp.com/terraform/cli/commands/validate

> Validate runs checks that verify whether a configuration is syntactically valid and internally consistent, regardless of any provided variables or existing state. It is thus primarily useful for general verification of reusable modules, including correctness of attribute names and value types.
> ...
> To verify configuration in the context of a particular run (a particular target workspace, input variable values, etc), use the terraform plan command instead, which includes an implied validation check.

This behavior is controlled by Terraform core's logic, rather than anything controllable on the provider side of the protocol. There's nothing we could change in terraform-plugin-framework or the lower level terraform-plugin-go module to influence this behavior. The closest open issue in my brief searching was https://github.com/hashicorp/terraform/issues/28104, however it may be worth creating a new issue: https://github.com/hashicorp/terraform/issues

Thanks again.
