### ISSUE TITLE
Support self reference for  Attribute Structure 

### ISSUE THREAD

**Issue by dreampuf** [hashicorp/terraform-plugin-framework#686]
### Module version

```
github.com/hashicorp/terraform-plugin-framework v1.1.1
```

### Use-cases

To have a simple solution of child structure which has a similar structure.

```
type ModelA struct {
    Id    types.Int64  `tfsdk:"id"`
    Type  types.String `tfsdk:"type"`
    ...
    Child    types.Object `tfsdk:"child"` // <-- This `ModelA.Child` reference to a similar structure `ModelB`. It doesn't have a child field.
}
type ModelB struct {
    Id    types.Int64  `tfsdk:"id"`
    Type  types.String `tfsdk:"type"`
    ...
    // no Child field in ModelB
}
```
 

### Attempted Solutions

Do we have a simpler way to do it? Or can terraform-plugin-framework support disable some fields for a particular object?

**Comment by bflad** [comment]
Hi @dreampuf 👋 Thank you for raising this feature request.

Given the example code you provided, I believe the Go programming language functionality that is representative of this is [type embedding](https://go.dev/doc/effective_go#embedding). For example:

```go
type CommonModel struct {
    Id    types.Int64  `tfsdk:"id"`
    Type  types.String `tfsdk:"type"`
}

type ModelA struct {
    CommonModel
    Child types.Object `tfsdk:"child"`
}

type ModelB struct {
  CommonModel
}
```

terraform-plugin-framework does not support type embedding for data handling at the moment. This feature request is being tracked in https://github.com/hashicorp/terraform-plugin-framework/issues/242. Since I believe that issue would be tracking this sort of request already, I'm going to close this new issue as a duplicate to focus discussions and efforts on the existing issue.

> Do we have a simpler way to do it?

You can try raising a topic in the [Plugin Development section of HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43), where more provider developers may be able to provide their experiences/examples rather than the limited number following this GitHub issue tracker for bug reports or feature requests with this Go module.

> Or can terraform-plugin-framework support disable some fields for a particular object?

I do not believe this is possible at the moment nor do I believe we could design a reasonable solution for this exact request given the current data handling. If it was a field tag based solution, it would still require two separate Go type definitions since the field tags are "local" to the current object/type.
