### ISSUE TITLE
Set, Map, and Object TF framework types throw errors when used

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/terraform-plugin-framework#700]
### Module version
```
1.2.0
```

### Relevant provider source code
```go
ElementType: types.MapType,
ElementType: types.SetType,
ElementType: types.ObjectType,
```

### Expected Behavior
According to the [documentation](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/attributes), these are the associated framework types, so they should function as expected.

### Actual Behavior
> types.MapType (type) is not an expression

### Additional Information
I cynically worked around the errors by importing the `basetypes` package, and then:
`ElementType: basetypes.MapType{},`

However, I am unsure if this is a true fix for the issue, and would not feel confident proposing a PR with that as the fix for this issue. This is especially because this workaround then causes a segfault analogous to #699.

**Comment by bflad** [comment]
Hi @mschuchard 👋 Thank you for raising this and sorry you ran into trouble here.

Terraform and the framework type system both delineate between "primitive" and "collection" types. Primitive types do not require anything additional to be functional, while collection types _must_ denote the underlying attribute or element types. 

More specifically with the framework type system implementation, originally everything was implemented within a single `types` package, however [it had extensibility issues with the primitive types](https://github.com/hashicorp/terraform-plugin-framework/issues/91) since those were not implemented as their own Go structure types. This was [mostly fixed with the implementation of the `types/basetypes` package](https://github.com/hashicorp/terraform-plugin-framework/pull/567), which introduced primitive types as their own types, however to maintain backwards compatibility with existing provider code the `types` package implementation kept support for the primitive types without the `{}`. Using `types/basetypes` always requires the `{}` (and for collection types, the `AttributeTypes` or `ElementType` field) since those are all Go structure types.

You can see the current quirks in the [`types` package Go documentation]( https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/types) where primitive types are variables and collection types are type aliases:

- https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/types#pkg-variables
- https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/types#pkg-types

For most providers developers, working with the `types` package may be slightly more readable, where the `types/basetypes` package is generally only _needed_ for creating custom types. Ideally, there wouldn't be two separate packages for the framework type system, but that particular detail was not rectified before the v1.0.0 release of the framework due to time constraints. The `types` and `types/basetypes` packages are now protected by major version compatibility promises, so we cannot introduce any breaking changes in the name of consistency until the next major version. I think our options to prevent this situation are quite limited. 😖 

Ideally, it should not be possible for provider developers to incorrectly create types in the first place. This could be achieved, for example, by breaking the `types` API in the next major version by replacing the variable and type aliases with functions (e.g. `func BoolType() basetypes.BoolType`, `func MapType(elementType attr.Type) basetypes.MapType`). Another less likely option could be removing the second `types` implementation altogether and requiring everyone to implement `basetypes` types with `{}` (and any "required" fields) correctly.

As for what to do _now_ given the current situation, I think there might be some hesitation with pointing provider developers directly at the `types/basetypes` implementations since it could be more confusing to change our recommendations and code examples between minor versions without knowing how we would _eventually_ prefer the framework type system to be implemented. We would not want developers to feel compelled to update their code now to later need to update it differently.

Over in https://github.com/hashicorp/terraform-plugin-framework/issues/695 we are exploring the option of expanding all the attribute/block/type documentation into separate, more manageable pages. With those extra pages, we could further get into more code examples and potentially provide a "Troubleshooting" section with the Go compiler error you mention. Do you think that might be reasonable from a documentation standpoint?

**Comment by mschuchard** [comment]
Thanks for the information. It is a bit unclear to me if this is pertaining to this issue, #699, or both in combination.

> while collection types must denote the underlying attribute or element types

Great! Where in the documentation can I find information about that? I was taking shots in the dark around how to specify the collection type fully in the schema, and could not arrive at any positive results. I also did try to workaround this with a dummy `NestedAttribute`, but that always resulted in the nested attribute being `null` seemingly because it was computed. This meant I could not `req.Config.Get` with any useful results. Should I be using e,g, `ElementType: basetypes.MapType{ElemType basetypes.StringType{}}`? All I need is the capability to specify something like a TF type `list(map)` or `set(object)` as an attribute and not block, but that may currently be impossible.

>Over in https://github.com/hashicorp/terraform-plugin-framework/issues/695 we are exploring the option of expanding all the attribute/block/type documentation into separate, more manageable pages.

I am familiar with that one as I commented already about my struggles with the typing and my appreciation for documentation expansion. I am unsure about others' experiences thus far, but I am not finding examples to cross-reference in the major providers where code is attempting to achieve the same kind of results that I am working towards. I code in many languages and the `types` package gives me "Rust vibes" so I feel like there is some familiarity there, but alternatively I may be mistaken about everything.

**Comment by bflad** [comment]
Thank you for the additional information. It's the end of my day, but I do want to provide you a quick answer here:

> All I need is the capability to specify something like a TF type list(map) or set(object) as an attribute and not block

In your schema, I would anticipate something like the below for `list(map(??))`:

```go
"list_of_map_attribute": schema.ListAttribute{
  ElementType: types.Map{
    ElemType: /* ... types.String, etc. */, // ElemType inside a Map is required (old naming convention)
  },
  // ... other attribute configuration ...
},
```

For the `set(object)` you have two options. You can _literally_ use a set of objects, or I'm guessing preferably, use a set nested attribute. The latter allows you to fully define behaviors on the underlying attributes, rather than just specify type information.

```go
"set_nested_attribute": schema.SetNestedAttribute{
  NestedObject: schema.NestedAttributeObject{
    // ... nested object configuration ...
  },
  // ... other attribute configuration ...
},
```

In your data models:

```go
type ExampleResourceModel struct {
  ListOfMapAttribute types.List `tfsdk:"list_of_map_attribute"`
  SetNestedAttribute types.Set `tfsdk:"set_nested_attribute"`
}

type SetNestedAttributeModel struct {
  // ... underlying attributes ...
}
```

And converting out (assuming a list of map of strings):

```go
var config ExampleResourceModel

resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)

if resp.Diagnostics.HasError() {
  return
}

// generally good to check config.ListOfMapAttribute.IsNull() or IsUnknown() before doing the below
// similarly with config.SetNestedAttribute.IsNull()/IsUnknown()

var listOfMaps []types.Map

resp.Diagnostics.Append(config.ElementsAs(ctx, &listOfMaps))

if resp.Diagnostics.HasError() {
  return
}

for _, listMap := range listOfMaps {
  var mapOfStrings map[string]types.String

  resp.Diagnostics.Append(listMap.ElementsAs(ctx, &mapOfStrings)...)

  if resp.Diagnostics.HasError() {
    return
  }

  // hopefully you're good from here :)
}

var setNestedAttribute SetNestedAttributeModel

resp.Diagnostics.Append(config.SetNestedAttribute.As(ctx, &setNestedAttribute)...)

if resp.Diagnostics.HasError() {
  return
}

// hopefully you're good from here :)
```

Complex attributes are tricky to talk about and write out code-wise, since there are multiple potential ways you can write the Go code or use the type system, but hopefully this extra context/example code is helpful. I apologize if any of the code is buggy above, I was trying to hastily write this before heading out. If you have further questions about this over the weekend, you may have good luck raising a topic on [HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43). I'll try to provide a better response to the rest next week.

**Comment by mschuchard** [comment]
Ok yes wow: that first block of code is exactly what I needed. I had no idea from the `types` documentation and source code that I could do that; I had assumed I needed to use `basetypes` to interface like that.

For the second and third blocks of code: I actually do not want nested attributes, but now I am curious because I would have thought the `SetNestedAttribute types.Set` would be a `[]SetNestedAttributeModel` instead of a `types.Set`?

> // generally good to check config.ListOfMapAttribute.IsNull() or IsUnknown() before doing the below

Good point.

`resp.Diagnostics.Append(listMap.ElementsAs(ctx, &mapOfStrings)...)`: This is probably more pedantic than anything else, but I have been wondering about this kind of code. This is probably a drawback to my knowledge of multiple languages because I become confused about the differences in behavior between them, but is that reference in the `ElementsAs` argument ensuring it stores the specific element of the map in the lambda from the `listOfMaps` enumerable even when it is the parameter/argument value to the `Diagnostics.Append`? In other words: later in that lambda scope, would I be dereferencing a `nil` pointer if attempted to access `mapOfStrings`? I would not think so, but I have been cautious and wary of trying that. I also assume it is overwritten on each iteration and not merged, but that is more curiosity than anything else.

Anyway: thanks so much for all of this, and expanded documentation for the `types` would definitely be great. You clearly know the package well, so I would hope you are documenting it. Also this is a super digression, but would the `types` package fix the issue with the Packer SDK being unable to upgrade to the new version of `go-cty`? Mart would probably know best since he gave me the info, but I am hopeful.

Also on an interesting note: someone on StackOverflow earlier today asked almost literally the same question as this issue's topic, but that person seemed to be using SDKv2. I informed the person I felt fairly certain an upgrade to the plugin framework was necessary because schema for `list(map)` in SDKv2 seems to result in blocks.

**Comment by mschuchard** [comment]
My apologies: I thought your reply above was functional for the current 1.2.0 version of this Go module. However, I understand now that your first example of:

```go
"list_of_map_attribute": schema.ListAttribute{
  ElementType: types.Map{
    ElemType: /* ... types.String, etc. */, // ElemType inside a Map is required (old naming convention)
  },
  // ... other attribute configuration ...
},
```

is a proposal for a future version since it throws the exact same multiple errors as my attempt. I will eagerly await the implementation of that functionality in the `types` package.

**Comment by bflad** [comment]
@mschuchard can you please show all of your code and the errors you are seeing? I do see that I typo'd a few things in my quick writing last week (e.g. `types.Map` instead of `types.MapType`). My apologies. I created and verified example code here: https://github.com/bflad/terraform-provider-framework/pull/1/files

> `resp.Diagnostics.Append(listMap.ElementsAs(ctx, &mapOfStrings)...)`: This is probably more pedantic than anything else, but I have been wondering about this kind of code. 

I would recommend reading about variadic functions in the Go programming language here: https://www.digitalocean.com/community/tutorials/how-to-use-variadic-functions-in-go

And peeking at the Go package documentation for each call:

- https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/diag#Diagnostics.Append
- https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/types/basetypes#MapValue.ElementsAs

One way to break it down is:

```go
diags := listMap.ElementsAs(ctx, &mapOfStrings)
// diags is a diag.Diagnostics (which itself is a type alias for []diag.Diagnostics)
resp.Diagnostics.Append(diagnostics...)
```

Its a coding style to remove the intermediate variable (`diags` above) if its not going to be used elsewhere or interfere with further code. You are welcome to split those apart as you wish.

> Also this is a super digression, but would the types package fix the issue with the Packer SDK being unable to upgrade to the new version of go-cty?

The terraform-plugin-framework Go module and its underlying `types` package is intended for Terraform Provider code. If there are other types of Go modules consuming this code, I think we would need to understand more context. The underlying terraform-plugin-go and terraform-plugin-framework type systems, while similar in some respects to `cty`, have no dependency on that type system or its Go module nor should affect upgrades of that Go module.
