### ISSUE TITLE
Failed to `Get` model for resource with computed `SingleNestedAttribute`

### ISSUE THREAD

**Issue by onematchfox** [hashicorp/terraform-plugin-framework#776]
### Module version
```
v1.3.1
```

### Relevant provider source code

Minimum reproducible example available at 
https://github.com/onematchfox/terraform-provider-scaffolding-framework/tree/demo/get-nested-computed-attributes-error

Contains a [single change](https://github.com/hashicorp/terraform-provider-scaffolding-framework/commit/0707d4f77c003104e8e04059357209896d522c07) from upstream/main to add a `Computed` `SingleNestedAttribute` to both the example data source and resource models.

### Terraform Configuration Files

```tf
resource "scaffolding_example" "test" {
  configurable_attribute = "foo"
}
```

### Expected Behavior

Calls to `req.Plan.Get(ctx, &data)` should succeed with model being returned with `ComputedNestedAttributes` set to `nil`.

### Actual Behavior

Call to `req.Plan.Get(ctx, &data)` succeeds in the data source but fails in the resource. This seems to be because the raw state in the resource plan has defaulted the value of the `computed_nested` to `UnknownValue` whereas in the data source the value of `computed_nested` in the plan is `nil`. Error returned is:
```
Error: Value Conversion Error
        
   with scaffolding_example.test,
   on terraform_plugin_test.tf line 2, in resource "scaffolding_example" "test":
   2: resource "scaffolding_example" "test" {

An unexpected error was encountered trying to build a value. This is always
an error in the provider. Please report the following to the provider
developer:

Received unknown value, however the target type cannot handle unknown values.
Use the corresponding `types` package type or a custom type that handles
unknown values.

Path: computed_nested
Target Type: *provider.ComputedObject
Suggested Type: basetypes.ObjectValue
```

### Steps to Reproduce

Run acceptance tests in the linked repository. Data source succeeds. Resource fails.

**Comment by chrismarget-j** [comment]
This error is complaining that the following struct element cannot distinguish between a `null` value and an `unknown` value:

```go
ComputedNestedAttributes *ComputedObject `tfsdk:"computed_nested"`
```

You'll have better luck defining it as:

```go
ComputedNestedAttributes types.Object `tfsdk:"computed_nested"`
```

**Comment by onematchfox** [comment]
Hi @chrismarget-j,

Thanks for the input. I get that that is what the error is saying. However, if I change to `types.Object`, then, AFAIK, I need to handle all the "marshalling" myself rather than relying on the framework to handle that for me. This seems unnecessary to me since the framework can handle this (as evidenced by the fact that there is no issue using the exact same implementation on a data source). Similarly, if I change `computed_nested` to `Optional` instead of `Computed`, then there's no problem. Or, alternatively, I can change `computed_nested` from `SingleNestedAttribute` to `SingleNestedBlock` and this is handled fine. However, in both of those cases, it means that this nested attribute/block is no longer "read-only".

I'm not sure why the plan on a resource needs to default all `Computed` attributes to `UnknownValue` when this doesn't happen on a data source?

**Comment by chrismarget-j** [comment]
> handle all the "marshalling" myself

That's what I do. Maybe there's a better/easier way?

> evidenced by the fact that there is no issue using the exact same implementation on a data source

Maybe this is evidence that a data source has no need of generating a plan, so the problem space is a little different?

> if I change `computed_nested` to `Optional` instead of `Computed`, then there's no problem.

When the element is `Optional`, but not `Computed` there are only two possibilities: `null` or "known". Adding `Computed` to the mix introduces a third possibility which can't be handled by a pointer (nil or not nil).

I struggled with this stuff early in my provider framework journey and decided it was easier (and better for my sanity) to ensure that every tfsdk-tagged struct element came from the types library, rather than attempting to consider all of the rules. There's probably subtleties here of which I'm not aware.

**Comment by bflad** [comment]
The answers from @chrismarget-j above pretty much summarize everything here.

Terraform's concept of a value being unknown is not a property that can be expressed purely with Go's built-in type system concepts, however that concept is very important for provider developers to understand/handle. It would be incorrect for the framework to assume what Go built-in representation is best for provider code in the case of an unknown value since it would ultimately need to be represented by overloading _some_ known value or awkwardly overloading the null value, essentially making it impossible to distinguish between unknown and whatever arbitrary choice was to be made. The framework could provide configurable options for provider developers to decide what do rather than the framework making its own arbitrary choice(s), but it was decided early on in the framework's design that the configurability was the same, if not more, confusing than providing a type system that could fully represent Terraform values. Another interesting aspect to this is that additional Terraform value information that cannot be represented by Go built-in representations, such as value sensitivity, partial unknown-ness, etc. is possible by implementing a separate type system and would further confuse or limit developer experience over time for those using Go built-in representations.

Since the framework appears to be working as expected here and there has been no discussion on this issue the last few weeks, I'm going to close this issue. If you have suggestions on how to better document this or improve error messaging, please do feel free to reach out. 👍
