### ISSUE TITLE
Alternatives for configuration and state consistency issue

### ISSUE THREAD

**Issue by dawiddzhafarov** [hashicorp/terraform-plugin-framework#789]
Hi,

We are beginning the process of migrating resources and data sources from plugin SDK to framework, however we are having trouble achieving the same behavior as before. Maybe You have some solutions/advices that could solve the problem(considered as a blocker right now) that we are facing during migration.

Problem description:
We are sending the attribute value (which in fact is a JSON) to the API, which can modify it, for example by removing empty arrays, adding default values. So those two values are not the same character to character, but they mean the same. We have no impact how the API works so we cannot do anything in that matter. We incorporated comparison logic into SemanticEquals. However we still cannot migrate such resource with this problem, as terraform demands consistency between configuration and plan. With plugin implementation, there was always value from the API in state and now, it has to be taken from the configuration if provided. What is more, during Import, the only value that can be put into the state is the one from the API, making it even more inconsistent. 

Previous behavior:
For fields that were both `Optional` and `Computed`, if You have specified it in the configuration, You could later overwrite such field (i.e., in Create operation) with different value (i.e., from the API). If such attribute wasn’t specified in the configuration, You could simply set it to any value. Is

Current behavior:
Currently, terraform requires consistency between plan and configuration, so it raises an error if we try to modify such attribute, if it was specified in the configuration. We have tried using attribute and resource plan modifiers, however they didn’t solve the issue. We have used Custom Types and Semantic Equals to achieve DiffSuppress functionality from the plugin SDK, but it’s not possible to set different value for such field, if it was configured.

Expected behavior:
We would like to have a possibility to set in state different value than was specified in the configuration for both Optional and Computed attributes. It is because we don’t want to change the behavior of already existing resources and such change makes it difficult.

Question is, is there any way to handle it differently or allow for the behavior I have described? Are there any plans on supporting it?

With regards,
Dawid

**Comment by bflad** [comment]
Hi @dawiddzhafarov 👋 Thank you for raising this and sorry for the delayed response.

> We would like to have a possibility to set in state different value than was specified in the configuration for both Optional and Computed attributes. It is because we don’t want to change the behavior of already existing resources and such change makes it difficult.
> 
> Question is, is there any way to handle it differently or allow for the behavior I have described? 

Terraform has data consistency rules with respect to configuration, plan, and state values. These rules are generally summarized in [Terraform Resource Instance Change Lifecycle](https://github.com/hashicorp/terraform/blob/main/docs/resource-instance-change-lifecycle.md), but as a quick rule of thumb for this specific question: if a value is configured, it _must_ be preserved with the same value in the state when applied.

The prior terraform-plugin-sdk has a special exemption for demoting the errors of some of these data consistency rules into warning logs, except when the value is referenced elsewhere in a configuration, which will almost always generate a similar data consistency error in that downstream resource. If you inspect Terraform runs with SDK-based resources, you will likely see these warning logs if you enable logging (e.g. `TF_LOG=TRACE terraform apply`). Newer Terraform provider SDKs intentionally do not allow this behavior to prevent this unpredictable behavior for Terraform practitioners and provider developers, especially since it tended to cause practitioners to report errors in the wrong place where the downstream provider developer could not do anything to prevent the issue since it was caused by an upstream provider breaking the data consistency rules.

For your use case, it sounds like custom types and semantic equality would be the expected solution (or otherwise massaging API responses to match the given configuration except for the purposes of drift detection during resource refresh). Please note that the framework's design of these is intended to match Terraform's design, so for example, changing a value with or without using a custom type semantic equality solution is intentionally not supported/enabled. Semantic equality is intended to prevent extraneous drift detection and data consistency errors if the new value is functionally equivalent to a prior value by preserving the prior value. If the API response includes more information than the configuration/plan value and that information is valuable for practitioners, then it may make the most sense to save that data into a separate attribute(s).

> Are there any plans on supporting it?

Any changes to Terraform's data consistency rules would need to be discussed with the Terraform core maintainers, since they are fundamental to Terraform's current design. If you would like to ask this same question to them, you could try posting this to the [Terraform core section of HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-core/27). If you would like to raise a specific design change proposal as a feature request, then the [core issue tracker](https://github.com/hashicorp/terraform/issues) is the best location.

---

Hopefully this answers your questions, but if you have further questions about migrating or provider development, then its best to raise the topic in the [Terraform plugin development section of HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43) where there are far more folks answering these sorts of queries. 👍
