### ISSUE TITLE
Path AtMapKey().AtName() doesnt work during validation

### ISSUE THREAD

**Issue by asdevcapybara** [hashicorp/terraform-plugin-framework#795]
### Module version
```
$ go list -m github.com/hashicorp/terraform-plugin-framework 
github.com/hashicorp/terraform-plugin-framework v1.3.2
```

### Relevant provider source code
Schema definition:
```go
resp.Schema = schema.Schema{
...
		Attributes: map[string]schema.Attribute{
			...
			"name_servers": schema.MapNestedAttribute{
				Required: true,
				Validators: []validator.Map{
					mapvalidator.SizeAtLeast(2),
				},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"ip": schema.StringAttribute{
							Optional: true,
							Computed: true,
							Default:  stringdefault.StaticString(""),
						},
						...
					},
				},
			},
		},
	}
```

Here is the code I try to use:
```go
func (r ResourceName) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	for key, NameServer := range data.NameServers {
    ...
			resp.Diagnostics.AddAttributeError(
				path.Root("name_servers").AtMapKey(key).AtName("ip"),
				"IP is not valid",
				"Provide real ip addr",
			)
	...
	}
}
```

### Terraform Configuration Files
```hcl
resource "..." "..." {
 ...
  name_servers = {
    "nameserver1" = {
      ip = "wrong_value"
    },
  }
}
```

### Debug Output
https://gist.github.com/asdevcapybara/8c7270da7d244209c8cbb3a3929d34e9

### Expected Behavior
According to the documentation (https://developer.hashicorp.com/terraform/plugin/framework/handling-data/paths#building-map-nested-attributes-paths) , error should point to the specific field, like:
```

$ terraform validate
╷
│ Error: IP is not valid
│ 
│   with ........,
│   on main.tf line 37, in resource "..." "...":
│   39:     "ip = "wrong_value"
│ 
│ Provide real ip addr
```

### Actual Behavior
It just pointing to the whole resource:
```

$ terraform validate
╷
│ Error: IP is not valid
│ 
│   with .......,
│   on main.tf line 30, in resource "..." "...":
│   30: resource "..." "..." {
│ 
│ Provide real ip addr
```

It almost work without `AtName()`, eg if we change the path line to :

```go
			resp.Diagnostics.AddAttributeError(
				path.Root("name_servers").AtMapKey(key),
				"IP is not valid",
				"Provide real ip addr",
			)
```

Then the error points to the key:

```
$ terraform validate
╷
│ Error: IP is not valid
│ 
│   with ........,
│   on main.tf line 37, in resource "..." "...":
│   37:     "nameserver1" = {
│ 
│ Provide real ip addr
```

### Steps to Reproduce
```
terraform validate 
```
and any other command when the ValidateConfig function is called

### References
The documentation:
https://developer.hashicorp.com/terraform/plugin/framework/handling-data/paths#building-map-nested-attributes-paths

**Comment by chrismarget** [comment]
This looks a bit like terraform [#33491](https://github.com/hashicorp/terraform/issues/33491).

I'm curious whether the debug trace indicated the same symptoms, but I can't read it.

**Comment by bflad** [comment]
Hi @asdevcapybara 👋 Thank you for raising this and sorry for the trouble here.

As far as we can tell, providers that build the expected path information for a diagnostic are sending this information appropriately across the protocol to Terraform core, which is responsible for showing the relevant Terraform configuration snippet when possible. It appears that support for this configuration snippet handling in Terraform core requires some additional changes to fully support nested attributes such as these. The issue for tracking this in Terraform core is https://github.com/hashicorp/terraform/issues/33491, if you want to 👍 and subscribe for updates.

Since it does not appear that there is anything we can do in _this_ Go module or the lower level terraform-plugin-go Go module to resolve this problem and there is already an issue for tracking this in the appropriate location, I'm going to close this issue. Please reach out if I am missing anything.
