### ISSUE TITLE
Attributes inside nested block are not validated

### ISSUE THREAD

**Issue by mkuzmin** [hashicorp/terraform-plugin-framework#805]
### Module version
```
1.3.2
```

### Terraform Configuration Files
This is an example with official provider to reproduce the issue easier. I get the same behavior with my custom code.

```hcl
resource "random_id" "server" {
  byte_length = 8
  keepers     = {
    # Unknown attribute
    qwerty = 123
    ami_id = "123"
  }
}
```

### Expected Behavior
Validation should fail:
```
Error: Unsupported argument
│ 
│   on project.tf line 9, in resource "random_id" "server":
│    9:   qwerty = 123
│ 
│ An argument named "qwerty" is not expected here.
```

### Actual Behavior
Error is ignored:
```
Terraform will perform the following actions:

  # random_id.server will be created
  + resource "random_id" "server" {
      + b64_std     = (known after apply)
      + b64_url     = (known after apply)
      + byte_length = 8
      + dec         = (known after apply)
      + hex         = (known after apply)
      + id          = (known after apply)
      + keepers     = {
          + "ami_id" = "123"
          + "qwerty" = "123"
        }
    }
```

**Comment by austinvalle** [comment]
Hi there @mkuzmin 👋🏻 !

The `random_id.keepers` attribute you're referencing in your reproduction doesn't have validation on it's attributes as it's an arbitrary map of values, represented as a `MapAttribute` of `types.StringType`.

https://github.com/hashicorp/terraform-provider-random/blob/d62a15b2ba285278698fbf0dde65d8022124c2c8/internal/provider/resource_id.go#L58

> I get the same behavior with my custom code.

Can you share the schema, terraform config, and error message of your code that you're expecting to produce a validation error?

**Comment by bflad** [comment]
Drive-by note to leave some additional breadcrumbs/linking/context: on the Terraform core side of things, https://developer.hashicorp.com/terraform/language/expressions/types#maps-objects is the relevant documentation here. It could potentially use some more verbiage about maps having arbitrary key names while objects have defined attribute names. That change would need to occur upstream. On the provider side of things, https://developer.hashicorp.com/terraform/plugin/framework/handling-data/attributes#map is potentially missing a word like "arbitrary" in front of "string keys". We do have plans to expand the framework type documentation via https://github.com/hashicorp/terraform-plugin-framework/issues/695 so its not all colocated on one page and maybe that separation via navigation could help.

**Comment by chrismarget-j** [comment]
I think I've seen the behavior described by @mkuzmin.

In my case, it happens in [an object](https://github.com/Juniper/terraform-provider-apstra/blob/2deb9ffbd939c772ab5c6625649f1a212bed6997/apstra/design/rack_type_leaf_switch.go#L93C1-L160C1) that's [nested within a map](https://github.com/Juniper/terraform-provider-apstra/blob/2deb9ffbd939c772ab5c6625649f1a212bed6997/apstra/design/rack_type.go#L60C1-L67C1).

The following terraform config validates okay in spite of `bogus_attribute`.

```hcl
terraform {
  required_providers {
    apstra = {
      source  = "Juniper/apstra"
      version = "0.21.0"
    }
  }
}

resource "apstra_rack_type" "r" {
  name                       = "test"
  fabric_connectivity_design = "l3clos"
  leaf_switches = {                    # this is a map
    foo = {                            # foo is the key, but the value at "foo" is an object
      logical_device_id = "ld_id"
      spine_link_speed  = "10G"
      spine_link_count  = 1
      bogus_attribute   = "you betcha" # <= I'd have expected a validation error here
    }
  }
}
```

**Comment by bflad** [comment]
One thing we could confirm is whether or not those extra keys/attribute names are actually passed across the protocol. They likely are _not_ since Terraform core should be using the provider schema information to build the configuration, proposed new state, and prior state data values that get sent across the protocol. We can try to get this information by setting the `TF_LOG_SDK_PROTO_DATA_DIR` environment variable and inspecting the `ValidateResourceConfig` and `PlanResourceChange` RPC request `Config` MessagePack data with a tool such as https://github.com/wader/fq.

My hunch though is that this is all behavior on the core side and the issue would need to be filed over there.

**Comment by bflad** [comment]
I spent a few minutes doing the investigative work mentioned above to check that the extraneous information is not something that is sent across the protocol and it seems to confirm that this is not something we can handle on the provider side of the protocol. Please feel free to double check in your own cases.

Given the following configuration:

```terraform
resource "framework_schema" "test" {
	single_nested_attribute = {
		single_nested_attribute_attribute = "value1"
		non_existent = "oops" # not in the schema
	}
}
```

Terraform core is sending only the known schema attribute information across the protocol during the `ValidateResourceConfig` RPC (e.g. `fq -d msgpack tovalue 1690227683787_ValidateResourceConfig_Request_Config.msgpack` in my case):

```json
    {
      "key": {
        "length": 23,
        "type": "fixstr",
        "value": "single_nested_attribute"
      },
      "value": {
        "length": 1,
        "pairs": [
          {
            "key": {
              "length": 33,
              "type": "str8",
              "value": "single_nested_attribute_attribute"
            },
            "value": {
              "length": 6,
              "type": "fixstr",
              "value": "value1"
            }
          }
        ],
        "type": "fixmap"
      }
    },
```

Therefore, it would require an enhancement in Terraform core (which parses the configuration and reads provider schemas) for Terraform to raise any sort of configuration error in these cases. My suggestion would be to file an issue in their issue tracker: https://github.com/hashicorp/terraform/issues

Please find some similar issue references (but nothing that is configuration _and_ provider schema specific) since Terraform's configuration handling behavior of allowing extra object attribute names may be more of a configuration design choice:

- https://github.com/hashicorp/terraform/issues/28696
- https://github.com/hashicorp/terraform/issues/28727
- https://github.com/hashicorp/terraform/issues/29204
- https://github.com/hashicorp/terraform/issues/32015
