### ISSUE TITLE
Optionally relax requirements of Config.Get, Plan.Get, and State.Get

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-framework#84]
### Module version

```
v0.2.0
```

### Use-cases

`Config.Get`, `Plan.Get`, and `State.Get` all require for unknown and null values to be explicitly handled, and will return an error if they're not. This can be annoying in certain situations, where unknown or null values don't matter--for example, computed-only fields will always be unknown in the plan, it's annoying to handle them explicitly instead of defaulting to the empty value, because there's no confusion about whether they were set or not.

### Attempted Solutions

We already actually have support for this built into the reflection code powering `Get`, it just isn't surfaced in `Get` right now.

### Proposal

Let's add `GetConfigOption`, `GetStateOption`, and `GetPlanOption` types that can adjust how `Get` works on those types, and add a third, variadic argument to `Get` that accepts those options. That allows for the default cause to continue working today, allows for the optional specification of the "relax, please" flag, and allows us room to add more flags in the future if it turns out we want other options.

**Comment by bflad** [comment]
Over in #498 there is a proposal for the opposite approach to this issue since we have learned quite a bit about default recommendations we can suggest to prevent issues. Since this issue was raised, there has also been the introduction of `attr.Value` conversion helpers such as `tfsdk.ConvertValue()` and `tfsdk.ValueAs()`.

There is a sense that aligning every schema attribute type (`attr.Type`) with an associated value type (`attr.Value) will prevent confusion, rather than having runtime errors raised to practitioners based on a complex set of rules that a provider developer might not be familiar with, or introducing a plethora of data handling options which provider developers must discover and understand. If using a non-framework-defined Go type is important for a use case, then custom provider-defined types and the conversion helpers are there. If fetching zero-values for null or unknown values is an important use case, then `attr.Value` implementations can already enable that.

We can of course revisit this in the future, but for now I'm going to close this issue.

Aside: In #447 we are considering making the framework-defined `types` value types zero-value null instead of an "invalid" value (which tends to be a zero-value of the underlying storage type). This is two-fold to prevent the creation of these "invalid" value types while also enabling use case where an API never sends a value, so making it null by default will play nicely with Terraform's data handling.
