### ISSUE TITLE
Feature flags for SDK behaviors

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-framework#86]
### Module version

```
v0.2.0
```

### Use-cases

As we build out new functionality into the framework, we're going to be introducing new features that happen outside of a provider developer's control. We've done our best to provide options structs for these so far, but for example changing every computed null value to unknown in the plan is currently something the framework does that providers have no control over. And while it's reasonable for the framework to have behaviors providers have no control over, it would be neat to let provider developers turn off behaviors instead of working around them, and would make the framework a little more flexible.

### Attempted Solutions

We've used options structs for this in a few places.

### Proposal

I'm proposing that we use `tfsdk.ServeOpts` as a way for providers to opt into or out of behaviors in the SDK, and that we develop a pattern for checking the values of these flags. This would likely involve threading a framework-controlled type through the provider, potentially through the context? But we should have some way of optionally enabling or disabling features based on explicit options defined by providers, even when the provider isn't directly involved in invoking the code the feature is contained within.

**Comment by bflad** [comment]
Long term, I think this approach is great and we should go with this type of design. While we are guessing that developers may want to control certain framework-defined behaviors, what those are and the associated code for reading them is more of an implementation detail of those features if or when the time comes.

As for this issue itself, it is a little hard to consider what a definition of done for this is since there's not a specific use case yet that is being requested by the community. Rather than leave this issue open and lingering, we can treat this issue as an agreement on a design. Let's go ahead and say "yes, use `ServeOpts` for controlling framework-defined behaviors, which are read via the context" rather than trying to attach any specific implementation here without a specific timeframe. If there are specific feature requests for this type of configuration with framework functionality, they should be created with bespoke issues describing the use cases. 👍
