### ISSUE TITLE
Proposal: Allow removing key from `Private` data

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-plugin-framework#910]
### Module version

```
github.com/hashicorp/terraform-plugin-framework v1.5.0
```

### Use-cases

Resource `Private` data may sometimes no longer be needed. There is currently no way to remove it.

### Attempted Solutions

Setting a key to `nil` or `""` causes an error, such as

> The value being supplied for key "aws_lb_listener.importing" is invalid.
> Please verify that the value is valid JSON.

### Proposal

Add a corresponding function `RemoveKey` to `*privatestate.ProviderData`.

**Comment by bflad** [comment]
Hey @gdavison 👋 Thank you for raising this and we should certainly support this in some manner.

As a workaround for now, does `SetKey(ctx, "key", []byte("null")` work for your use case? That should at least insert a literal JSON `null` as the value and appears to work in my quick `SetKey()` unit test trial -- leaving the key with a literal `null` value. Not exactly the most ideal, but should operate fairly similar from your end, I would think.

In terms of actual key _removal_, I think we could support either a new `RemoveKey(key string)` method and/or update the existing `SetKey()` so it can support `nil` to remove the key. The latter might actually be preferable because it is likely that other developers may try exactly what you did and expect it to work. Semantically it feels like it would be performing the same change as what a `RemoveKey()` method would do under the hood anyways.

**Comment by gdavison** [comment]
Yes, I'm using the `"null"` workaround. I'm using the values `true` or `null`, so I check the content for equality instead of simple presence.

`SetKey` supporting `nil` would work
