### ISSUE TITLE
Expose Provider Version configured in the client's required_providers {}

### ISSUE THREAD

**Issue by SkymineGit** [hashicorp/terraform-plugin-framework#920]
### Module version

```
github.com/hashicorp/terraform-plugin-framework v1.5.0
```

### Use-cases

I'd like to use the provider `version` attribute configured under the terraform `required_providers {}` on the client side to pass it as input attribute to an API that the provider interacts with to do what it needs to do based on the version.

The use case is to have provider versions in sync with the API it interacts in the backend, otherwise it can be that the provider schema and the backend API are out of sync in terms of attributes and theirs values and will cause failures. Multiple version of the provider can be used so I can't use only the latest version and always be in sync.

### Attempted Solutions

I couldn't find anywhere in the framework the provider version configured in `required_providers {}`. There is a Terraform Version attribute under the provider ConfigureRequest
```
type ConfigureRequest struct {
    // TerraformVersion is the version of Terraform executing the request.
    // This is supplied for logging, analytics, and User-Agent purposes
    // only. Providers should not try to gate provider behavior on
    // Terraform versions.
    TerraformVersion string
```

I've worked around this by creating a provider configuration attribute and capturing the same version in the  `required_providers {}` in that attribute. With this method, there is a risk of the user setting up different versions between  `required_providers {}` and the provider configuration attribute which will cause issues with the backend API.

### Proposal

I couldn't call myself even a junior go developer so it's hard for me to provide a solution but it seams innocent enough to me if exposed in the same manner as the Terraform Version approach.

**Comment by chrismarget-j** [comment]
Rather than collecting the constraint value (which may be configured sloppily or not at all), you could detect the actual version of the provider.

[This provider](https://github.com/Juniper/terraform-provider-apstra) does exactly that.

It works like this:

- [Global variables `commit` and `tag`](https://github.com/Juniper/terraform-provider-apstra/blob/2ddac8d857da05d275eb7ce2fdd8bec9e5e20d1f/apstra/provider.go#L56C1-L57C1) are [populated from the actual git tag and commit hash during the release process](https://github.com/Juniper/terraform-provider-apstra/blob/2ddac8d857da05d275eb7ce2fdd8bec9e5e20d1f/.goreleaser.yml#L21C1-L23C1).
- If they're not set (dev builds not using the release process), [default values are used instead](https://github.com/Juniper/terraform-provider-apstra/blob/2ddac8d857da05d275eb7ce2fdd8bec9e5e20d1f/apstra/provider.go#L62C1-L77C9).
- These strings are [part of the struct which implements `provider.Provider`](https://github.com/Juniper/terraform-provider-apstra/blob/2ddac8d857da05d275eb7ce2fdd8bec9e5e20d1f/apstra/provider.go#L92C1-L97C1), so they're available when the provider's `Configure()` is run.
- In `Confugre()`, [they become part of `reap.ResourceData` and `resp.DataSourceData`](https://github.com/Juniper/terraform-provider-apstra/blob/2ddac8d857da05d275eb7ce2fdd8bec9e5e20d1f/apstra/provider.go#L424C1-L435C1), so they're available for use when resources or data sources talk to the API.
